import 'package:args/command_runner.dart';
import 'package:mason_logger/mason_logger.dart';
import 'package:path/path.dart' as p;

import '../utils/file_utils.dart';
import '../utils/project_inspector.dart';
import '../utils/project_manifest.dart';

/// Sanity-checks an existing project previously scaffolded by moarch.
class DoctorCommand extends Command<int> {
  /// Creates the doctor command.
  DoctorCommand({required Logger logger}) : _logger = logger {
    argParser
      ..addOption(
        'path',
        abbr: 'p',
        help: 'Target project path (defaults to current directory).',
        defaultsTo: '.',
      )
      ..addFlag(
        'fix',
        negatable: false,
        help: 'Apply the fixes that can be applied without a decision.',
      );
  }

  final Logger _logger;

  @override
  String get name => 'doctor';

  @override
  String get description =>
      'Check an existing project for common scaffolding issues.';

  @override
  Future<int> run() async {
    final targetPath = p.absolute(argResults?['path'] as String? ?? '.');
    final shouldFix = argResults?['fix'] as bool? ?? false;

    _logger.info('');
    _logger.info('🩺 moarch doctor — checking $targetPath');

    final manifest = ProjectManifest.load(targetPath);
    if (manifest != null) {
      _logger.info('   generated by moarch v${manifest.version}');
    }
    _logger.info('');

    final findings = await ProjectInspector.inspect(targetPath);

    if (findings.isEmpty) {
      _logger.success('  ✓  No issues found.');
      _logger.info('');
      return 0;
    }

    for (final finding in findings) {
      _report(finding);
    }

    final fixable = findings.where((f) => f.isFixable).toList();

    if (!shouldFix) {
      _logger.info('');
      if (fixable.isNotEmpty) {
        _logger.info('  ${fixable.length} of ${findings.length} can be fixed '
            'automatically — run: moarch doctor --fix');
      }
      _logger.err('${findings.length} issue(s) found.');
      _logger.info('');
      return 1;
    }

    if (fixable.isEmpty) {
      _logger.info('');
      _logger.warn('  Nothing here can be fixed automatically.');
      _logger.err('${findings.length} issue(s) found.');
      _logger.info('');
      return 1;
    }

    _logger.info('');
    final progress = _logger.progress('Applying ${fixable.length} fix(es)');
    FileUtils.beginSession();

    final applied = <String>[];
    try {
      for (final finding in fixable) {
        applied.add(await finding.fix!());
      }
      progress.complete('Fixes applied');
    } catch (e) {
      progress.fail('Failed: $e');
      FileUtils.rollback();
      _logger.info('  Rolled back partially applied fixes.');
      return 1;
    }

    _logger.info('');
    for (final description in applied) {
      _logger.info('  + $description');
    }

    // Re-inspect rather than assume: a fix reports what it did, not whether
    // the project as a whole came out clean.
    final remaining = await ProjectInspector.inspect(targetPath);
    _logger.info('');
    if (remaining.isEmpty) {
      _logger.success('  ✓  No issues remaining.');
      _logger.info('');
      return 0;
    }

    _logger.warn('  ${remaining.length} issue(s) still need a decision:');
    for (final finding in remaining) {
      _report(finding);
    }
    _logger.info('');
    return 1;
  }

  void _report(Diagnostic finding) {
    switch (finding.severity) {
      case DiagnosticSeverity.error:
        _logger.err('  ✗  ${finding.message}');
      case DiagnosticSeverity.warning:
        _logger.warn('  !  ${finding.message}');
      case DiagnosticSeverity.info:
        _logger.info('  ·  ${finding.message}');
    }
    final hint = finding.hint;
    if (hint != null) {
      for (final line in wrap(hint, 68)) {
        _logger.info('       $line');
      }
    }
  }

  /// Wraps [text] to [width] columns so a long hint stays readable in a
  /// terminal instead of running off the edge.
  static List<String> wrap(String text, int width) {
    final words = text.split(RegExp(r'\s+')).where((w) => w.isNotEmpty);
    final lines = <String>[];
    var current = StringBuffer();

    for (final word in words) {
      if (current.isEmpty) {
        current.write(word);
      } else if (current.length + 1 + word.length <= width) {
        current.write(' $word');
      } else {
        lines.add(current.toString());
        current = StringBuffer(word);
      }
    }
    if (current.isNotEmpty) lines.add(current.toString());
    return lines;
  }
}
