import 'dart:io';

import 'package:args/command_runner.dart';
import 'package:mason_logger/mason_logger.dart';
import 'package:path/path.dart' as p;

import '../utils/project_inspector.dart';
import '../utils/project_manifest.dart';
import '../utils/text_diff.dart';
import '../utils/widget_catalog.dart';
import '../version.dart';

/// What refreshing one generated file would mean.
enum UpdateStatus {
  /// On disk already matches the current template.
  upToDate,

  /// moarch wrote it, nobody edited it, and the template has since changed.
  /// Safe to overwrite.
  stale,

  /// The template changed *and* the file was edited after generation.
  /// Overwriting would discard the user's work.
  conflicted,

  /// The template changed but there is no record of what moarch wrote, so
  /// edits can't be ruled out. Treated as [conflicted] for safety.
  unknown,
}

/// One generated file considered by `moarch update`.
class UpdateCandidate {
  /// Creates a candidate.
  const UpdateCandidate({
    required this.spec,
    required this.path,
    required this.status,
    required this.current,
    required this.generated,
  });

  /// The catalog entry this file came from.
  final WidgetSpec spec;

  /// Absolute path to the file on disk.
  final String path;

  /// What updating it would mean.
  final UpdateStatus status;

  /// The file's current content.
  final String current;

  /// What the current template would write.
  final String generated;

  /// Whether this file can be refreshed without losing user edits.
  bool get isSafe => status == UpdateStatus.stale;

  /// Whether refreshing risks discarding edits.
  bool get needsDecision =>
      status == UpdateStatus.conflicted || status == UpdateStatus.unknown;
}

/// Refreshes generated UI-kit widgets against the templates of the running
/// moarch version.
///
/// This is the answer to a scaffolder's central problem: code generated by an
/// older version goes stale, and the user has no way to tell an improvement
/// they want from an edit of their own they'd lose. The manifest written at
/// generation time makes that distinction — untouched files refresh silently,
/// edited ones are never overwritten without an explicit choice.
class UpdateCommand extends Command<int> {
  /// Creates the update command.
  UpdateCommand({required Logger logger}) : _logger = logger {
    argParser
      ..addOption(
        'path',
        abbr: 'p',
        help: 'Target project path (defaults to current directory).',
        defaultsTo: '.',
      )
      ..addFlag(
        'dry-run',
        negatable: false,
        help: 'Report what would change without writing anything.',
      )
      ..addFlag(
        'yes',
        abbr: 'y',
        negatable: false,
        help: 'Refresh every unmodified file without prompting.',
      )
      ..addFlag(
        'force',
        negatable: false,
        help: 'Also overwrite files you have edited (discards those edits).',
      )
      ..addFlag(
        'diff',
        abbr: 'd',
        negatable: false,
        help: 'Print the changes for each file instead of a summary line.',
      );
  }

  final Logger _logger;

  @override
  String get name => 'update';

  @override
  String get description =>
      'Refresh generated widgets against the current moarch templates.';

  @override
  String get invocation => 'moarch update [<widget>...]';

  @override
  Future<int> run() async {
    final targetPath = p.absolute(argResults?['path'] as String? ?? '.');
    final libPath = p.join(targetPath, 'lib');
    final dryRun = argResults?['dry-run'] as bool? ?? false;
    final assumeYes = argResults?['yes'] as bool? ?? false;
    final force = argResults?['force'] as bool? ?? false;
    final showDiff = argResults?['diff'] as bool? ?? false;
    final only = argResults?.rest ?? const <String>[];

    if (!Directory(libPath).existsSync()) {
      _logger
          .err('No lib/ directory at $targetPath — is this a Flutter project?');
      return 1;
    }

    final unknown =
        only.where((name) => WidgetCatalog.byName(name) == null).toList();
    if (unknown.isNotEmpty) {
      _logger.err('Unknown widget(s): ${unknown.join(', ')}');
      _logger.info('Run `moarch create widget --list` to see valid names.');
      return 1;
    }

    _logger.info('');
    _logger.info('🔄 moarch update — v$packageVersion');

    final manifest = ProjectManifest.load(targetPath);
    if (manifest == null) {
      _logger.info('');
      _logger.warn('  No ${ProjectManifest.fileName} in this project.');
      _logger
          .info('  Without it moarch cannot tell an untouched generated file');
      _logger.info('  from one you edited, so every changed file is listed as');
      _logger.info('  needing review rather than refreshed automatically.');
    } else {
      _logger.info('   project generated by moarch v${manifest.version}');
    }
    _logger.info('');

    final candidates = _collect(targetPath, libPath, manifest, only);

    if (candidates.isEmpty) {
      _logger.info('  No generated widgets found under lib/shared/widgets/.');
      _logger.info('');
      return 0;
    }

    final changed =
        candidates.where((c) => c.status != UpdateStatus.upToDate).toList();
    final upToDate = candidates.length - changed.length;

    if (changed.isEmpty) {
      _logger.success(
          '  ✓  All ${candidates.length} generated widget(s) are up to date.');
      _logger.info('');
      return 0;
    }

    final safe = changed.where((c) => c.isSafe).toList();
    final needsDecision = changed.where((c) => c.needsDecision).toList();

    _logger.info('  $upToDate up to date · ${safe.length} can be refreshed · '
        '${needsDecision.length} need review');
    _logger.info('');

    if (safe.isNotEmpty) {
      _logger.info('  Unmodified since moarch generated them:');
      for (final candidate in safe) {
        _describe(candidate, showDiff: showDiff);
      }
      _logger.info('');
    }

    if (needsDecision.isNotEmpty) {
      _logger
          .info('  Changed by you since generation — not touched by default:');
      for (final candidate in needsDecision) {
        _describe(candidate, showDiff: showDiff);
      }
      _logger.info('');
    }

    if (dryRun) {
      _logger.info('  Dry run — nothing was written.');
      _logger.info('');
      return 0;
    }

    final toWrite = <UpdateCandidate>[
      ...safe,
      if (force) ...needsDecision,
    ];

    if (toWrite.isEmpty) {
      _logger.info('  Nothing to refresh automatically.');
      if (needsDecision.isNotEmpty) {
        _logger.info('  Review the diffs above (`moarch update --diff`), then');
        _logger.info('  re-apply by hand, or overwrite with `--force`.');
      }
      _logger.info('');
      return 0;
    }

    if (force && needsDecision.isNotEmpty) {
      _logger.warn('  --force will discard your edits to '
          '${needsDecision.length} file(s).');
    }

    if (!assumeYes) {
      final confirmed = _logger.confirm(
        '  Refresh ${toWrite.length} file(s)?',
        defaultValue: !force,
      );
      if (!confirmed) {
        _logger.info('  Cancelled — nothing was written.');
        _logger.info('');
        return 0;
      }
    }

    final progress = _logger.progress('Refreshing ${toWrite.length} file(s)');
    final updated = ProjectManifest.loadOrCreate(targetPath);

    try {
      for (final candidate in toWrite) {
        await File(candidate.path).writeAsString(candidate.generated);
        updated.record(targetPath, candidate.path, candidate.generated);
      }
      // Files that were already current are recorded too, so a project that
      // predates the manifest stops reporting "unknown" on the next run.
      for (final candidate in candidates) {
        if (candidate.status == UpdateStatus.upToDate) {
          updated.record(targetPath, candidate.path, candidate.current);
        }
      }
      await updated.save(targetPath);
      progress.complete('Refreshed');
    } catch (e) {
      progress.fail('Failed: $e');
      return 1;
    }

    _logger.info('');
    for (final candidate in toWrite) {
      _logger.info('  ↻ shared/widgets/${candidate.spec.file}');
    }
    _logger.info('');
    _logger.success('  Updated to moarch v$packageVersion.');
    _logger.info('  Review the changes with `git diff` before committing.');
    _logger.info('');
    return 0;
  }

  /// Builds the candidate list by comparing each generated widget on disk
  /// against what the current template would write.
  List<UpdateCandidate> _collect(
    String projectRoot,
    String libPath,
    ProjectManifest? manifest,
    List<String> only,
  ) {
    final widgetsRoot = p.join(libPath, 'shared', 'widgets');
    final present = ProjectInspector.generatedWidgets(libPath);
    final filtered = only.isEmpty
        ? present
        : present.where((spec) => only.contains(spec.name)).toList();

    final candidates = <UpdateCandidate>[];
    for (final spec in filtered) {
      final path = p.join(widgetsRoot, spec.file);
      final current = File(path).readAsStringSync();
      final generated = ProjectInspector.widgetSource(libPath, spec);

      final UpdateStatus status;
      if (!TextDiff.differ(current, generated)) {
        status = UpdateStatus.upToDate;
      } else {
        final recorded = manifest?.recordedHash(projectRoot, path);
        if (recorded == null) {
          status = UpdateStatus.unknown;
        } else if (recorded == ProjectManifest.hashContent(current)) {
          status = UpdateStatus.stale;
        } else {
          status = UpdateStatus.conflicted;
        }
      }

      candidates.add(UpdateCandidate(
        spec: spec,
        path: path,
        status: status,
        current: current,
        generated: generated,
      ));
    }

    candidates.sort((a, b) => a.spec.name.compareTo(b.spec.name));
    return candidates;
  }

  void _describe(UpdateCandidate candidate, {required bool showDiff}) {
    final stat = TextDiff.stat(candidate.current, candidate.generated);
    final label = switch (candidate.status) {
      UpdateStatus.unknown => ' (no generation record)',
      UpdateStatus.conflicted => ' (edited)',
      _ => '',
    };
    _logger.info('    ${candidate.spec.title.padRight(20)} '
        'shared/widgets/${candidate.spec.file}  '
        '+${stat.added} -${stat.removed}$label');

    if (!showDiff) return;
    for (final line
        in TextDiff.unified(candidate.current, candidate.generated)) {
      switch (line.kind) {
        case '+':
          _logger.info('      ${green.wrap('+${line.text}')}');
        case '-':
          _logger.info('      ${red.wrap('-${line.text}')}');
        default:
          _logger.info('      ${darkGray.wrap(' ${line.text}')}');
      }
    }
    _logger.info('');
  }
}
