import 'dart:io';

import 'package:args/command_runner.dart';
import 'package:mason_logger/mason_logger.dart';
import 'package:moarch/src/commands/create/create_widget_command.dart';
import 'package:moarch/src/utils/project_manifest.dart';
import 'package:moarch/src/utils/widget_catalog.dart';
import 'package:path/path.dart' as p;
import 'package:test/test.dart';

void main() {
  late Directory tempDir;
  late String root;

  String at(String relative) => p.joinAll([root, ...p.posix.split(relative)]);

  String pathOf(String widget) => at(
        'lib/shared/widgets/${WidgetCatalog.byName(widget)!.file}',
      );

  String sourceOf(String widget) => WidgetCatalog.sourceFor(
        WidgetCatalog.byName(widget)!,
        WidgetVariants.detect(at('lib')),
      );

  Map<String, String> manifestFiles() =>
      ProjectManifest.load(root)?.files ?? const {};

  /// Puts a file on disk the way something other than this command did — a
  /// copy from another project, or a run that predates the manifest.
  Future<void> place(String relative, String content) async {
    final path = at(relative);
    await Directory(p.dirname(path)).create(recursive: true);
    await File(path).writeAsString(content);
  }

  late CommandRunner<int> runner;

  Future<int?> run(List<String> args) =>
      runner.run(['widget', '--path', at('lib'), ...args]);

  setUp(() async {
    tempDir = await Directory.systemTemp.createTemp('moarch_widget_cmd');
    root = tempDir.path;
    await Directory(at('lib')).create(recursive: true);
    await File(at('pubspec.yaml')).writeAsString('name: scratch\n');

    final command = CreateWidgetCommand(logger: Logger(level: Level.quiet));
    runner = CommandRunner<int>('moarch', 'test')..addCommand(command);
  });

  tearDown(() async => tempDir.delete(recursive: true));

  test('records every widget it writes', () async {
    expect(await run(['bottom-nav']), 0);

    final recorded = manifestFiles();
    expect(recorded,
        contains('lib/shared/widgets/navigation/app_bottom_nav.dart'));
    // Its dependencies are generated by the same run, so they are recorded by
    // it too — an untracked dependency is as invisible to `update` as an
    // untracked widget.
    expect(
        recorded, contains('lib/shared/widgets/inputs/app_input_style.dart'));
  });

  test('records a widget already on disk that matches the templates', () async {
    // The case a re-run hits: the file is there, nothing is written, and
    // without this the manifest would never learn about it.
    await place(
      'lib/shared/widgets/navigation/app_bottom_nav.dart',
      sourceOf('bottom-nav'),
    );

    expect(await run(['bottom-nav']), 0);

    const key = 'lib/shared/widgets/navigation/app_bottom_nav.dart';
    expect(manifestFiles(), contains(key));
    expect(
      manifestFiles()[key],
      ProjectManifest.hashContent(sourceOf('bottom-nav')),
    );
  });

  test('leaves an edited widget out of the manifest', () async {
    // Its content is the user's, and vouching for it would let `update`
    // overwrite the edit silently.
    await place(
      'lib/shared/widgets/navigation/app_bottom_nav.dart',
      '${sourceOf('bottom-nav')}\n// mine\n',
    );

    expect(await run(['bottom-nav']), 0);

    expect(
      manifestFiles(),
      isNot(contains('lib/shared/widgets/navigation/app_bottom_nav.dart')),
    );
    // And the edit itself survives, as it always has.
    expect(
      File(pathOf('bottom-nav')).readAsStringSync(),
      endsWith('// mine\n'),
    );
  });

  test('`all` leaves nothing it generated untracked, run twice', () async {
    expect(await run(['all']), 0);

    final onDisk = Directory(at('lib/shared/widgets'))
        .listSync(recursive: true)
        .whereType<File>()
        .where((f) => f.path.endsWith('.dart'))
        .map((f) => ProjectManifest.relativeKey(root, f.path))
        .toList();

    expect(onDisk, isNotEmpty);
    expect(manifestFiles().keys, containsAll(onDisk));

    // The second run writes nothing at all — the manifest it saves has to be
    // the one it loaded, not an empty one.
    final before = manifestFiles();
    expect(await run(['all']), 0);
    expect(manifestFiles(), before);
  });

  test('a run that writes nothing new still adopts what it finds', () async {
    // Every file present and none of them tracked: the manifest is written
    // even though the run created nothing.
    expect(await run(['bottom-nav']), 0);
    await File(p.join(root, ProjectManifest.fileName)).delete();

    expect(await run(['bottom-nav']), 0);

    expect(
      manifestFiles(),
      contains('lib/shared/widgets/navigation/app_bottom_nav.dart'),
    );
  });
}
