import 'dart:io';

import 'package:path/path.dart' as p;

/// Utility helpers for keeping generated project dependencies in sync.
class PubspecUtils {
  PubspecUtils._();

  /// Ensures default dependency entries are present in a target pubspec file.
  static Future<void> ensureDependencies(
    String projectPath, {
    required List<String> dependencies,
    List<String> devDependencies = const <String>[],
  }) async {
    final pubspecFile = File(p.join(projectPath, 'pubspec.yaml'));

    if (!await pubspecFile.exists()) {
      await pubspecFile.writeAsString(_defaultPubspec(
        dependencies: dependencies,
        devDependencies: devDependencies,
      ));
      return;
    }

    var content = await pubspecFile.readAsString();

    content = _ensureSection(
      content,
      'dependencies',
      dependencies,
    );

    content = _ensureSection(
      content,
      'dev_dependencies',
      devDependencies,
    );

    await pubspecFile.writeAsString(content);
  }

  /// Ensures asset entries are present under the Flutter section of a target pubspec file.
  static Future<void> ensureAssets(String projectPath,
      {required List<String> assets}) async {
    final pubspecFile = File(p.join(projectPath, 'pubspec.yaml'));

    if (!await pubspecFile.exists()) {
      await pubspecFile.writeAsString(_defaultPubspec(
        dependencies: const <String>[],
        devDependencies: const <String>[],
        assets: assets,
      ));
      return;
    }

    var content = await pubspecFile.readAsString();
    content = _ensureFlutterAssets(content, assets);
    await pubspecFile.writeAsString(content);
  }

  static String _defaultPubspec({
    required List<String> dependencies,
    required List<String> devDependencies,
    List<String> assets = const <String>[],
  }) {
    final dependencyBlock = dependencies.map((entry) => '  $entry').join('\n');
    final devBlock = devDependencies.map((entry) => '  $entry').join('\n');
    final assetBlock = assets.map((entry) => '    - $entry').join('\n');

    return '''name: app\n
version: 1.0.0+1\ndescription: Generated by moarch\nenvironment:\n  sdk: ">=3.0.0 <4.0.0"\n\ndependencies:\n$dependencyBlock\n\nflutter:\n  assets:\n$assetBlock\n\ndev_dependencies:\n$devBlock\n''';
  }

  static String _ensureFlutterAssets(String content, List<String> assets) {
    if (assets.isEmpty) return content;

    final lines = content.split('\n');
    final flutterStart = lines.indexWhere(
      (line) =>
          line.trim() == 'flutter:' &&
          !line.startsWith('  ') &&
          !line.startsWith('\t'),
    );

    if (flutterStart == -1) {
      return '$content\n\nflutter:\n  assets:\n'
          '${assets.map((e) => '    - $e').join('\n')}\n';
    }

    final existingAssets = <String>{};
    var assetsSectionIndex = -1;
    // Track the line AFTER the last asset entry so we append, not prepend.
    var assetsInsertPosition = -1;

    for (var i = flutterStart + 1; i < lines.length; i++) {
      final line = lines[i];
      if (line.trim().isEmpty) continue;

      // Left-aligned = left the flutter section entirely.
      if (!line.startsWith('  ') && !line.startsWith('\t')) break;

      if (assetsSectionIndex == -1) {
        if (line.trim() == 'assets:' || line.trim().startsWith('assets:')) {
          assetsSectionIndex = i;
          assetsInsertPosition = i + 1; // default: insert right after header
        }
        continue;
      }

      // Inside the assets block.
      if (line.trim().startsWith('- ')) {
        existingAssets.add(line.trim().substring(2).trim());
        assetsInsertPosition = i + 1; // advance past each known entry
        continue;
      }

      // Hit the next flutter sub-key — stop collecting.
      break;
    }

    final missing =
        assets.where((entry) => !existingAssets.contains(entry)).toList();
    if (missing.isEmpty) return content;

    final insertLines = <String>[
      if (assetsSectionIndex == -1) '  assets:',
      ...missing.map((entry) => '    - $entry'),
    ];

    final insertPosition =
        assetsSectionIndex == -1 ? flutterStart + 1 : assetsInsertPosition;

    lines.insertAll(insertPosition, insertLines);
    return lines.join('\n');
  }

  static String _ensureSection(
    String content,
    String sectionName,
    List<String> entries,
  ) {
    if (entries.isEmpty) return content;

    final existingEntries = <String>{};
    final lines = content.split('\n');

    final sectionStart =
        lines.indexWhere((line) => line.trim() == '$sectionName:');

    if (sectionStart == -1) {
      final block =
          '\n$sectionName:\n${entries.map((entry) => '  $entry').join('\n')}\n';
      return '$content$block';
    }

    var insertPosition = sectionStart + 1;
    for (var i = sectionStart + 1; i < lines.length; i++) {
      final line = lines[i];
      if (line.trim().isEmpty) continue;

      // Left the section entirely — back to zero indentation.
      if (!line.startsWith('  ') && !line.startsWith('\t')) {
        insertPosition = i;
        break;
      }

      insertPosition = i + 1;

      // Only top-level (2-space) keys are dependency names. Deeper-nested
      // lines (e.g. `sdk: flutter` under `flutter:`) belong to the entry
      // above them and must not be mistaken for the end of the section.
      if (RegExp(r'^  \S').hasMatch(line)) {
        final entry = line.trim();
        if (entry.contains(':')) {
          existingEntries.add(entry.split(':').first.trim());
        }
      }
    }

    final missing = entries.where((entry) {
      final name = entry.split(':').first.trim();
      return !existingEntries.contains(name);
    }).toList();

    if (missing.isEmpty) return content;

    lines.insertAll(
      insertPosition,
      missing.expand((entry) => entry.split('\n').map(
            (line) => line.startsWith('    ') ? line : '  $line',
          )),
    );
    return lines.join('\n');
  }

  /// Ensures key: value flag entries are present directly under the flutter: section.
  static Future<void> ensureFlutterFlags(
    String projectPath, {
    required List<String> flags,
  }) async {
    final pubspecFile = File(p.join(projectPath, 'pubspec.yaml'));
    if (!await pubspecFile.exists()) return;

    var content = await pubspecFile.readAsString();
    content = _ensureFlutterFlags(content, flags);
    await pubspecFile.writeAsString(content);
  }

  static String _ensureFlutterFlags(String content, List<String> flags) {
    if (flags.isEmpty) return content;

    final lines = content.split('\n');
    final flutterStart = lines.indexWhere(
      (line) =>
          line.trim() == 'flutter:' &&
          !line.startsWith('  ') &&
          !line.startsWith('\t'),
    );

    if (flutterStart == -1) {
      final block = flags.map((f) => '  $f').join('\n');
      return '$content\n\nflutter:\n$block\n';
    }

    // Collect existing keys directly under flutter: (depth-1 only, not nested)
    final existingKeys = <String>{};
    var insertPosition = flutterStart + 1;

    for (var i = flutterStart + 1; i < lines.length; i++) {
      final line = lines[i];
      if (line.trim().isEmpty) continue;

      // Left the flutter section entirely
      if (!line.startsWith('  ') && !line.startsWith('\t')) {
        insertPosition = i;
        break;
      }

      // Only direct children (exactly 2-space indent), not nested entries
      if (RegExp(r'^  \S').hasMatch(line)) {
        existingKeys.add(line.trim().split(':').first.trim());
        insertPosition = i + 1;
      }
    }

    final missing = flags.where((flag) {
      final key = flag.split(':').first.trim();
      return !existingKeys.contains(key);
    }).toList();

    if (missing.isEmpty) return content;

    lines.insertAll(insertPosition, missing.map((f) => '  $f'));
    return lines.join('\n');
  }
}
