import '../templates/ui/dialogs_templates.dart';
import '../templates/ui/modals_templates.dart';
import '../templates/ui/shared_templates.dart';

/// One entry in the shared-widget kit: everything needed to generate a widget
/// on demand and to document it in `docs/UI_KIT.md`.
class WidgetSpec {
  /// Creates a widget catalog entry.
  WidgetSpec({
    required this.name,
    required this.title,
    required this.file,
    required this.template,
    required this.category,
    required this.description,
    this.deps = const [],
    this.packages = const [],
    this.common = false,
    this.needsRouter = false,
  });

  /// CLI slug, e.g. `switch` → `moarch create widget switch`.
  final String name;

  /// Human-facing class name, e.g. `AppSwitch`.
  final String title;

  /// Path relative to `lib/shared/widgets`, e.g. `inputs/app_switch.dart`.
  final String file;

  /// Produces the widget's source.
  final String Function() template;

  /// Grouping used by the generated catalog doc.
  final String category;

  /// One-line summary for the catalog doc.
  final String description;

  /// Other widget [name]s this one imports (pulled in automatically).
  final List<String> deps;

  /// pubspec dependency lines this widget needs, e.g. `mo_2fa_code: `.
  final List<String> packages;

  /// Generated by `moarch init` out of the box.
  final bool common;

  /// Imports `config/router/app_router.dart` — needs the GoRouter option.
  final bool needsRouter;
}

/// The shared-widget kit `moarch` can scaffold: a lean common set on `init`,
/// everything else via `moarch create widget <name>`.
abstract final class WidgetCatalog {
  /// Category order used by [markdown] and `--list`.
  static const List<String> categories = [
    'Inputs',
    'Buttons & icons',
    'Layout & content',
    'Feedback & loading',
    'Overlays',
    'Media',
    'Navigation',
    'Preview',
  ];

  /// Every widget in the kit, grouped by [categories] order.
  ///
  /// The preview screen is appended separately so its dependency list can be
  /// derived from [_kit] rather than hand-maintained — it claims to pull in
  /// the whole kit, and that stays true as widgets are added.
  static final List<WidgetSpec> all = [
    ..._kit,
    WidgetSpec(
      name: 'design-system',
      title: 'DesignSystemView',
      file: 'design_system_view.dart',
      template: SharedTemplates.designSystemView,
      category: 'Preview',
      needsRouter: true,
      deps: [for (final spec in _kit) spec.name],
      description:
          'A screen previewing the kit in light/dark. Pulls in every other widget.',
    ),
  ];

  static final List<WidgetSpec> _kit = [
    // ── Inputs ────────────────────────────────────────────────────────────────
    WidgetSpec(
      name: 'input-config',
      title: 'AppInputConfig',
      file: 'inputs/app_input_config.dart',
      template: SharedTemplates.appInputConfig,
      category: 'Inputs',
      common: true,
      description:
          'One file the whole input family reads: label placement, default variant/type/shape/size, border weights, size metrics.',
    ),
    WidgetSpec(
      name: 'input-style',
      title: 'AppInputStyle',
      file: 'inputs/app_input_style.dart',
      template: SharedTemplates.appInputStyle,
      category: 'Inputs',
      common: true,
      deps: ['input-config'],
      description:
          'Resolves variant + type + size into an InputDecoration; the base every input builds on.',
    ),
    WidgetSpec(
      name: 'input-title',
      title: 'InputTitle',
      file: 'inputs/input_title.dart',
      template: SharedTemplates.inputTitle,
      category: 'Inputs',
      common: true,
      deps: ['input-style'],
      description:
          'Label with an optional required asterisk, shown above a field.',
    ),
    WidgetSpec(
      name: 'input-format',
      title: 'AppInputFormat',
      file: 'inputs/app_input_format.dart',
      template: SharedTemplates.appInputFormat,
      category: 'Inputs',
      common: true,
      description:
          'Field formats (email, money, phone, card…) plus the formatters they type with; each one resolves to a keyboard, autofill hints and a validation rule.',
    ),
    WidgetSpec(
      name: 'input',
      title: 'AppInput',
      file: 'inputs/app_input.dart',
      template: SharedTemplates.appInput,
      category: 'Inputs',
      common: true,
      deps: ['input-style', 'input-title', 'input-format'],
      description:
          'Text field driven by an AppInputFormat: live input formatting, validation, a password eye, and variant/type/shape/size.',
    ),
    WidgetSpec(
      name: 'picker-sheet',
      title: 'CupertinoPickerSheet',
      file: 'inputs/cupertino_picker_sheet.dart',
      template: SharedTemplates.cupertinoPickerSheet,
      category: 'Inputs',
      description:
          'Cancel/Done bottom sheet around an iOS wheel, on the app\'s own surface colors — what the date and time fields open off Android.',
    ),
    WidgetSpec(
      name: 'date-input',
      title: 'AppDateInput',
      file: 'inputs/app_date_input.dart',
      template: SharedTemplates.dateInput,
      category: 'Inputs',
      deps: ['input-style', 'input-title', 'picker-sheet'],
      description:
          'Read-only field that opens the date picker its platform expects: the Material calendar on Android, the iOS wheel in a sheet elsewhere.',
    ),
    WidgetSpec(
      name: 'time-input',
      title: 'AppTimeInput',
      file: 'inputs/app_time_input.dart',
      template: SharedTemplates.timeInput,
      category: 'Inputs',
      deps: ['input-style', 'input-title', 'picker-sheet'],
      description:
          'Read-only field that opens the time picker its platform expects: the Material clock on Android, the iOS wheel in a sheet elsewhere.',
    ),
    WidgetSpec(
      name: 'dropdown',
      title: 'AppDropdownInput',
      file: 'inputs/app_dropdown_input.dart',
      template: SharedTemplates.appDropdown,
      category: 'Inputs',
      deps: ['input-style', 'input-title'],
      description: 'Generic id/label dropdown that reads any entity list.',
    ),
    WidgetSpec(
      name: 'checkbox',
      title: 'AppCheckbox',
      file: 'inputs/app_checkbox.dart',
      template: SharedTemplates.appCheckbox,
      category: 'Inputs',
      deps: ['input-style'],
      description: 'Variant-colored checkbox, square or circular.',
    ),
    WidgetSpec(
      name: 'checkbox-label',
      title: 'AppCheckboxLabel',
      file: 'inputs/app_checkbox_label.dart',
      template: SharedTemplates.appCheckboxLabel,
      category: 'Inputs',
      deps: ['checkbox'],
      description:
          'AppCheckbox paired with a tappable label and optional subtitle.',
    ),
    WidgetSpec(
      name: 'switch',
      title: 'AppSwitch',
      file: 'inputs/app_switch.dart',
      template: SharedTemplates.appSwitch,
      category: 'Inputs',
      deps: ['input-style'],
      description: 'On/off toggle for settings rows.',
    ),
    WidgetSpec(
      name: 'segmented',
      title: 'AppSegmented',
      file: 'inputs/app_segmented.dart',
      template: SharedTemplates.appSegmented,
      category: 'Inputs',
      deps: ['input-style'],
      description: 'Exclusive segmented control (Day/Week/Month-style).',
    ),
    WidgetSpec(
      name: 'choice-chip',
      title: 'AppChoiceChip',
      file: 'inputs/app_choice_chip.dart',
      template: SharedTemplates.appChoiceChip,
      category: 'Inputs',
      deps: ['input-style'],
      description: 'Selectable chip for tag/filter rows.',
    ),
    WidgetSpec(
      name: 'radio-group',
      title: 'AppRadioGroup',
      file: 'inputs/app_radio_group.dart',
      template: SharedTemplates.appRadioGroup,
      category: 'Inputs',
      deps: ['input-style'],
      description: 'Single-select labeled radio list (modern RadioGroup API).',
    ),
    WidgetSpec(
      name: 'slider',
      title: 'AppSlider',
      file: 'inputs/app_slider.dart',
      template: SharedTemplates.appSlider,
      category: 'Inputs',
      deps: ['input-style'],
      description: 'Variant-colored slider with an optional value label.',
    ),
    WidgetSpec(
      name: 'otp',
      title: 'AppOtpInput',
      file: 'inputs/app_otp_input.dart',
      template: SharedTemplates.appOtpInput,
      category: 'Inputs',
      deps: ['input-style', 'input-title'],
      packages: ['mo_2fa_code: '],
      description: 'One-time-code / OTP field powered by mo_2fa_code.',
    ),
    WidgetSpec(
      name: 'search-field',
      title: 'AppSearchField',
      file: 'inputs/app_search_field.dart',
      template: SharedTemplates.appSearchField,
      category: 'Inputs',
      deps: ['input-style', 'icon-button'],
      description:
          'Search input with a leading icon and a styleable clear button that appears when there is text.',
    ),
    WidgetSpec(
      name: 'stepper',
      title: 'AppStepper',
      file: 'inputs/app_stepper.dart',
      template: SharedTemplates.appStepper,
      category: 'Inputs',
      deps: ['input-style'],
      description:
          'Quantity stepper (− value +) that clamps itself to a min/max range.',
    ),

    // ── Buttons & icons ───────────────────────────────────────────────────────
    WidgetSpec(
      name: 'button',
      title: 'AppButton',
      file: 'buttons/app_button.dart',
      template: SharedTemplates.appButton,
      category: 'Buttons & icons',
      common: true,
      description:
          'Filled/outlined/ghost button with variant/shape/size, loading + disabled states.',
    ),
    WidgetSpec(
      name: 'leading-icon',
      title: 'AppLeadingIcon',
      file: 'icons/app_leading_icon.dart',
      template: SharedTemplates.appLeadingIcon,
      category: 'Buttons & icons',
      common: true,
      description:
          'Colored icon-in-a-box building block for list tiles, dialogs and cards.',
    ),
    WidgetSpec(
      name: 'icon-button',
      title: 'AppIconButton',
      file: 'buttons/app_icon_button.dart',
      template: SharedTemplates.appIconButton,
      category: 'Buttons & icons',
      description:
          "AppLeadingIcon's tappable sibling: ripple, haptics, tooltip, loading and disabled states.",
    ),

    // ── Layout & content ──────────────────────────────────────────────────────
    WidgetSpec(
      name: 'single-scroll-view',
      title: 'AppSingleScrollView',
      file: 'layouts/app_single_scroll_view.dart',
      template: SharedTemplates.appSingleScrollView,
      category: 'Layout & content',
      description:
          'Scrollable page body with the safe area, page padding and keyboard dismissal already decided; optional viewport fill and keyboard inset.',
    ),
    WidgetSpec(
      name: 'list-tile',
      title: 'AppListTile',
      file: 'lists/app_list_tile.dart',
      template: SharedTemplates.appListTile,
      category: 'Layout & content',
      description: 'Settings/menu row: leading, title/subtitle, trailing, tap.',
    ),
    WidgetSpec(
      name: 'card',
      title: 'AppCard',
      file: 'cards/app_card.dart',
      template: SharedTemplates.appCard,
      category: 'Layout & content',
      description:
          'Elevated/filled/outlined surface container, optionally tappable.',
    ),
    WidgetSpec(
      name: 'card-tile',
      title: 'AppCardTile',
      file: 'lists/app_card_tile.dart',
      template: SharedTemplates.appCardTile,
      category: 'Layout & content',
      deps: ['card', 'list-tile'],
      description:
          'AppListTile on its own AppCard surface — a standalone tappable row.',
    ),
    WidgetSpec(
      name: 'badge',
      title: 'AppBadge',
      file: 'indicators/app_badge.dart',
      template: SharedTemplates.appBadge,
      category: 'Layout & content',
      description: 'Count or dot badge over a child (e.g. a nav icon).',
    ),
    WidgetSpec(
      name: 'tag',
      title: 'AppTag',
      file: 'indicators/app_tag.dart',
      template: SharedTemplates.appTag,
      category: 'Layout & content',
      description: 'Small status pill — Active / Pending / Failed.',
    ),
    WidgetSpec(
      name: 'section-header',
      title: 'AppSectionHeader',
      file: 'lists/app_section_header.dart',
      template: SharedTemplates.appSectionHeader,
      category: 'Layout & content',
      description:
          'Heading above a group of rows: title, optional subtitle, optional "See all" action.',
    ),
    WidgetSpec(
      name: 'expansion-tile',
      title: 'AppExpansionTile',
      file: 'lists/app_expansion_tile.dart',
      template: SharedTemplates.appExpansionTile,
      category: 'Layout & content',
      description:
          'Borderless collapsible section that nests cleanly inside an AppCard.',
    ),

    // ── Feedback & loading ────────────────────────────────────────────────────
    WidgetSpec(
      name: 'loading-data',
      title: 'AppLoadingData',
      file: 'loadings/app_loading_data.dart',
      template: SharedTemplates.appLoadingData,
      category: 'Feedback & loading',
      common: true,
      description: 'Full-screen centered spinner for a loading route.',
    ),
    WidgetSpec(
      name: 'loading-overlay',
      title: 'AppLoadingActionOverlay',
      file: 'loadings/app_loading_action_overlay.dart',
      template: SharedTemplates.appLoadingAction,
      category: 'Feedback & loading',
      description:
          'Full-screen blocking overlay with a spinner and rotating reassurance messages.',
    ),
    WidgetSpec(
      name: 'skeleton-list',
      title: 'AppSkeletonList',
      file: 'loadings/app_skeleton_list.dart',
      template: SharedTemplates.appSkeletonList,
      category: 'Feedback & loading',
      packages: ['skeletonizer: '],
      description: 'Shimmering placeholder list for content that is loading.',
    ),
    WidgetSpec(
      name: 'screen-lock',
      title: 'AppScreenLock',
      file: 'loadings/app_screen_lock.dart',
      template: SharedTemplates.appScreenLock,
      category: 'Feedback & loading',
      description:
          'Freezes a screen (PopScope + AbsorbPointer) while an action is in flight.',
    ),
    WidgetSpec(
      name: 'error-view',
      title: 'ErrorView',
      file: 'error_view.dart',
      template: SharedTemplates.errorView,
      category: 'Feedback & loading',
      common: true,
      description: 'Inline error state with icon, message and optional retry.',
    ),
    WidgetSpec(
      name: 'empty-view',
      title: 'EmptyView',
      file: 'empty_view.dart',
      template: SharedTemplates.emptyView,
      category: 'Feedback & loading',
      common: true,
      description: 'Inline empty state with icon, message and optional action.',
    ),
    WidgetSpec(
      name: 'banner',
      title: 'AppBanner',
      file: 'feedback/app_banner.dart',
      template: SharedTemplates.appBanner,
      category: 'Feedback & loading',
      deps: ['tag', 'icon-button'],
      description:
          'Inline status message for state that persists — the calm counterpart to AppToast. Shares AppTagStatus with AppTag.',
    ),
    WidgetSpec(
      name: 'progress-bar',
      title: 'AppProgressBar',
      file: 'feedback/app_progress_bar.dart',
      template: SharedTemplates.appProgressBar,
      category: 'Feedback & loading',
      deps: ['input-style'],
      description:
          'Determinate or indeterminate linear progress, with an optional caption and percentage.',
    ),

    // ── Overlays ──────────────────────────────────────────────────────────────
    WidgetSpec(
      name: 'dialogs',
      title: 'AppDialogs',
      file: 'overlays/app_dialogs.dart',
      template: DialogsTemplates.appDialog,
      category: 'Overlays',
      common: true,
      needsRouter: true,
      description:
          'Context-free animated dialog helper (via rootNavigatorKey).',
    ),
    WidgetSpec(
      name: 'modals',
      title: 'AppBottomModals',
      file: 'overlays/app_bottom_modals.dart',
      template: ModalsTemplates.appBottomModals,
      category: 'Overlays',
      common: true,
      needsRouter: true,
      description: 'Context-free bottom-sheet helper (via rootNavigatorKey).',
    ),
    WidgetSpec(
      name: 'confirm-dialog',
      title: 'AppConfirmDialog',
      file: 'overlays/app_confirm_dialog.dart',
      template: DialogsTemplates.confirmDialog,
      category: 'Overlays',
      common: true,
      needsRouter: true,
      deps: ['button', 'leading-icon', 'dialogs'],
      description:
          'Confirm/cancel dialog built from AppButton + AppLeadingIcon.',
    ),
    WidgetSpec(
      name: 'toast',
      title: 'AppToast',
      file: 'overlays/app_toast.dart',
      template: SharedTemplates.appToast,
      category: 'Overlays',
      common: true,
      description:
          'Themed success/error/warning/info toast on ScaffoldMessenger.',
    ),
    WidgetSpec(
      name: 'bottom-sheet',
      title: 'AppBottomSheetScaffold',
      file: 'overlays/app_bottom_sheet_scaffold.dart',
      template: SharedTemplates.appBottomSheetScaffold,
      category: 'Overlays',
      common: true,
      description:
          'Bottom-sheet inside: styleable drag handle, optional title and close button, content padding.',
    ),

    // ── Media ─────────────────────────────────────────────────────────────────
    WidgetSpec(
      name: 'avatar',
      title: 'AppAvatar',
      file: 'media/app_avatar.dart',
      template: SharedTemplates.appAvatar,
      category: 'Media',
      packages: ['cached_network_image: '],
      description: 'Circular/rounded avatar with initials fallback.',
    ),
    WidgetSpec(
      name: 'image',
      title: 'AppImage',
      file: 'media/app_image.dart',
      template: SharedTemplates.appImage,
      category: 'Media',
      packages: ['cached_network_image: '],
      description: 'Network/asset image with placeholder and shape options.',
    ),

    // ── Navigation ────────────────────────────────────────────────────────────
    WidgetSpec(
      name: 'bottom-nav',
      title: 'AppBottomNav',
      file: 'navigation/app_bottom_nav.dart',
      template: SharedTemplates.appBottomNav,
      category: 'Navigation',
      description: 'Themed NavigationBar wrapper with typed destinations.',
    ),
    WidgetSpec(
      name: 'app-bar',
      title: 'AppAppBar',
      file: 'navigation/app_app_bar.dart',
      template: SharedTemplates.appAppBar,
      category: 'Navigation',
      deps: ['icon-button'],
      description:
          'PreferredSizeWidget AppBar with an optional subtitle and an AppIconButton back button — tonal by default — that only shows when the route can pop.',
    ),
    WidgetSpec(
      name: 'step-indicator',
      title: 'AppStepIndicator',
      file: 'navigation/app_step_indicator.dart',
      template: SharedTemplates.appStepIndicator,
      category: 'Navigation',
      deps: ['input-style'],
      description:
          'Progress through a multi-step flow, as dots, bars or numbered steps.',
    ),
  ];

  /// Every catalog slug.
  static List<String> get names => all.map((w) => w.name).toList();

  /// The widgets generated by `moarch init`.
  static List<WidgetSpec> get common => all.where((w) => w.common).toList();

  /// Looks up a spec by its CLI slug, or null if unknown.
  static WidgetSpec? byName(String name) {
    for (final spec in all) {
      if (spec.name == name) return spec;
    }
    return null;
  }

  /// Resolves [requested] to themselves plus all transitive [WidgetSpec.deps],
  /// de-duplicated. Unknown names are ignored (validate before calling).
  static List<WidgetSpec> resolve(Iterable<String> requested) {
    final resolved = <String, WidgetSpec>{};
    void visit(String name) {
      if (resolved.containsKey(name)) return;
      final spec = byName(name);
      if (spec == null) return;
      resolved[name] = spec;
      for (final dep in spec.deps) {
        visit(dep);
      }
    }

    for (final name in requested) {
      visit(name);
    }
    return resolved.values.toList();
  }

  /// The `docs/UI_KIT.md` catalog content.
  static String markdown() {
    final buffer = StringBuffer()
      ..writeln('# UI Kit — shared widgets')
      ..writeln()
      ..writeln(
          'Generated by **moarch**. These widgets live under `lib/shared/widgets/`')
      ..writeln(
          'and share one vocabulary: `variant` (primary/secondary/tertiary/danger),')
      ..writeln('`type`, `shape` and `size`.')
      ..writeln()
      ..writeln(
          'Rows marked ✅ are generated by `moarch init`. Add any other with:')
      ..writeln()
      ..writeln('```bash')
      ..writeln(
          'moarch create widget <name>     # e.g. moarch create widget switch')
      ..writeln(
          'moarch create widget all        # the whole kit + the preview screen')
      ..writeln(
          'moarch create widget --list     # print this catalog in the terminal')
      ..writeln('```')
      ..writeln()
      ..writeln(
          'Widget dependencies are pulled in automatically, and any pub packages a')
      ..writeln(
          'widget needs are added to `pubspec.yaml` (run `flutter pub get` after).')
      ..writeln();

    for (final category in categories) {
      final items = all.where((w) => w.category == category).toList();
      if (items.isEmpty) continue;
      buffer
        ..writeln('## $category')
        ..writeln()
        ..writeln('| Widget | `create widget` | Init | Notes |')
        ..writeln('| --- | --- | :---: | --- |');
      for (final w in items) {
        final notes = <String>[w.description];
        if (w.packages.isNotEmpty) {
          final pkgs =
              w.packages.map((p) => p.replaceAll(':', '').trim()).join(', ');
          notes.add('_pkg: ${pkgs}_');
        }
        if (w.needsRouter) notes.add('_needs GoRouter_');
        buffer.writeln(
          '| `${w.title}` | `${w.name}` | ${w.common ? '✅' : ''} | ${notes.join(' ')} |',
        );
      }
      buffer.writeln();
    }
    return buffer.toString();
  }
}
