/// The conventions of a moarch project that the test generators write
/// against, in one place so the unit and integration generators agree.
abstract final class TestGenConventions {
  /// What every generated test file carries, and what a re-run looks for
  /// before overwriting a file: one without it is hand-maintained.
  static const marker = 'GENERATED BY moarch';

  /// The first line of every generated test file.
  static const header =
      '// $marker (`moarch create tests`). Delete this '
      'line once you edit the file, and a re-run leaves it alone.';

  /// The markers the standalone `mogen_unit_tests` / `mogen_integration_tests`
  /// packages wrote. `moarch create tests` replaced both, so their output
  /// still counts as generated — re-running over a project that used them
  /// refreshes those files instead of skipping every one as hand-written.
  static const legacyMarkers = [
    'GENERATED BY mogen_unit_tests',
    'GENERATED BY mogen_integration_tests',
  ];

  /// Whether [content] is a file a generator wrote and may overwrite.
  static bool isGenerated(String content) =>
      content.contains(marker) || legacyMarkers.any(content.contains);

  /// What an error-path stub throws.
  ///
  /// A concrete `AppException` every moarch project already declares — the
  /// sealed hierarchy's `ServerException` — rather than a test-only factory
  /// that would have to live in production code.
  static const errorValue = "const ServerException(message: 'test')";

  /// The import [errorValue] and `isA<AppException>()` need.
  static String appExceptionImport(String packageName) =>
      "import 'package:$packageName/core/errors/app_exception.dart';";

  /// The import that brings `getIt` into a test, for dependencies a Riverpod
  /// notifier reads out of the locator.
  static String injectorImport(String packageName) =>
      "import 'package:$packageName/config/di/injector.dart';";
}
