import '../../utils/state_management.dart';

/// The instructions a coding agent reads before it touches the project.
///
/// `AGENTS.md` is the file the agents converge on (Codex, Cursor, Copilot,
/// Gemini and Zed read it as-is); `CLAUDE.md` is one line that imports it, so
/// Claude Code reads the same text rather than a copy that drifts.
///
/// The README explains the project to a person, with the reasoning. This is
/// the other audience: rules stated flatly, the paths they apply to, and the
/// commands that prove a change is done. Every section is built from what the
/// project has, like the README, and both are catalog entries — so
/// `moarch update agents` keeps it true as the templates move on, which is the
/// point of generating it at all.
class AgentsTemplates {
  AgentsTemplates._();

  /// Returns `AGENTS.md` for a project.
  static String agentsMd({
    required String projectName,
    required StateManagement stateManagement,
    bool withDio = false,
    bool withFirebase = false,
    bool withRouter = false,
    bool withAuthFeature = false,
    bool withDarkTheme = false,
    bool withStatusColors = false,
    bool withLocalization = false,
    bool withEasyLocalization = false,
    bool withFeatureModule = false,
  }) {
    final bloc = stateManagement.isBloc;
    return <String>[
      _header(projectName),
      _commands(),
      _layout(bloc: bloc, withRouter: withRouter),
      _architecture(
        bloc: bloc,
        withDio: withDio,
        withFirebase: withFirebase,
        withFeatureModule: withFeatureModule,
      ),
      bloc ? _blocRules() : _riverpodRules(),
      _ui(withDarkTheme: withDarkTheme, withStatusColors: withStatusColors),
      _addingAFeature(bloc: bloc, withRouter: withRouter),
      if (withLocalization || withEasyLocalization)
        _localization(easy: withEasyLocalization),
      _generated(withAuthFeature: withAuthFeature),
      _done(bloc: bloc),
    ].join('\n');
  }

  /// Returns `CLAUDE.md`: Claude Code's `@` import of [agentsMd], so there is
  /// one set of instructions rather than two that disagree.
  static String claudeMd() => '''
# CLAUDE.md

@AGENTS.md

<!-- The instructions live in AGENTS.md, which every coding agent reads; this
     file only imports them for Claude Code. Put anything Claude-specific below
     this comment. Both files are generated by moarch — `moarch update agents
     claude-md` refreshes them, and never overwrites one you have edited. -->
''';

  static String _header(String projectName) =>
      '''
# AGENTS.md — $projectName

Instructions for coding agents working in this repository. Generated by
[moarch](https://pub.dev/packages/moarch) from the options the project was
scaffolded with; `README.md` explains the same project to a person, with the
reasoning behind each rule.

The rules below are the project's conventions, not suggestions. When one of
them blocks what you were asked to do, say so instead of working around it.
''';

  static String _commands() => '''
## Commands

The Flutter SDK is pinned by FVM (`.fvmrc`). Always go through `fvm`, never a
bare `flutter` or `dart` — the one on `PATH` may be a different version.

```bash
fvm flutter pub get
fvm dart run build_runner build --delete-conflicting-outputs   # after editing a model or .env
fvm dart format .
fvm flutter analyze
fvm flutter test
```

`build_runner` writes every `*.freezed.dart` and `*.g.dart`, including
`lib/config/env/app_env.g.dart`. Those files are gitignored and must never be
edited by hand: until they exist the project does not analyze, which is
expected, not a bug to fix.

Scaffolding goes through the moarch CLI rather than being written by hand, so
the new files match the rest and the tooling can still refresh them:

| Command | Use it to |
|---|---|
| `moarch create feature <name>` | Add a feature — all layers, registered in the locator |
| `moarch create model <feature> <name> [--from-json sample.json]` | Add a freezed model to a feature |
| `moarch create widget <name>` | Add a widget from the UI kit (`moarch create widget --list`) |
| `moarch create tests [feature]` | Generate unit + integration tests from the code — re-run after adding methods |
| `moarch update --list` | See which generated files are stale or edited |
| `moarch doctor` | Check the project for known problems |
''';

  static String _layout({required bool bloc, required bool withRouter}) {
    final holder = bloc
        ? 'blocs/        # <x>_bloc.dart, <x>_event.dart, <x>_state.dart\n'
              '      pages/        # <x>_page.dart — provides the bloc, what a route points at\n'
        : 'notifiers/    # <x>_notifier.dart — AsyncNotifier + its provider\n'
              '      states/       # <x>_state.dart\n';
    return '''
## Layout

```
lib/
  config/
    di/            # get_it: injector.dart + one module per layer
    env/           # AppEnv (envied) — the only reader of .env
    theme/         # AppTheme${withRouter ? '\n    router/        # GoRouter + AppRoutes' : ''}
  core/
    constants/     # AppConstants (palette, spacing, radii, motion curves), ApiConstants
    errors/        # AppException — the one error type the UI sees
    network/ security/ services/ utils/
  features/<feature>/
    data/
      datasources/   # where the bytes come from
      repositories/  # <x>_repository_impl.dart
    domain/
      models/        # the feature's freezed model(s)
      repositories/  # the interface the presentation layer depends on
    presentation/
      $holder      views/        # <x>_view.dart — the screen
  shared/
    widgets/       # the UI kit — catalogued in docs/UI_KIT.md
    views/         # screens that belong to no feature
test/
  unit/  integration/
```
''';
  }

  static String _architecture({
    required bool bloc,
    required bool withDio,
    required bool withFirebase,
    required bool withFeatureModule,
  }) {
    final boundary = [
      if (withDio) '`safeApiCall` (`core/network/safe_api_call.dart`)',
      if (withFirebase)
        '`safeFirebaseCall` (`core/network/safe_firebase_call.dart`)',
    ];
    final sdks = [if (withDio) 'Dio', if (withFirebase) 'Firebase'];
    return '''
## Architecture rules

- **No entity layer.** A feature's data type is the freezed model in
  `domain/models/`, used directly by the repository interface, the state and
  the view. Do not add `domain/entities/`, `toEntity()` / `fromEntity()`
  mappers or a second class mirroring a model.
- **No use-case classes.** The ${bloc ? 'bloc' : 'notifier'} calls the repository interface.
- `domain/` imports no Flutter${sdks.isEmpty ? '' : ', no ${sdks.join(', no ')}'} and nothing from `data/`.
- The ${bloc ? 'bloc' : 'notifier'} depends on the repository **interface**, never on a
  datasource or on `*_repository_impl.dart`.
- **One error type reaches the UI: `AppException`** (`core/errors/`).
  ${boundary.isEmpty ? 'The datasource translates' : 'The datasource wraps its calls in ${boundary.join(' / ')}, which translate'}
  transport errors into it. Catch `AppException` and show its `message`; never
  show a raw exception or leave a `catch` empty.
- **Dependencies come from get_it**, registered in `lib/config/di/`:
  `external_module.dart` (SDK handles), `core_module.dart` (services),
  `data_module.dart` (datasources, repositories)${withFeatureModule ? ', `feature_module.dart`\n  (long-lived services one feature owns — sockets, engines — and `openScope` /\n  `closeScope` for what one flow owns)' : ''}${bloc ? ', `presentation_module.dart`\n  (blocs, as factories)' : ''}. `injector.dart` only calls them.${bloc ? '' : '\n  Notifiers are **not** registered: they stay behind their Riverpod provider\n  and read what they need with `getIt<T>()`.'}
- The `// moarch:registrations` comments in the modules are anchors
  `moarch create feature` inserts above. Never move or delete them.
- Configuration comes from `AppEnv` (`lib/config/env/app_env.dart`). Add a key
  to `.env`, `.env.example` and an `@EnviedField` together; never read `.env`
  any other way, and never commit `.env`.
''';
  }

  static String _riverpodRules() => r'''
## State — Riverpod

- A feature's state holder is an `AsyncNotifier<XState>` in
  `presentation/notifiers/`, with `ActionNotifierMixin`
  (`core/utils/action_notifier.dart`).
- The state class holds the screen's data plus the one-shot
  `isLoadingAction` / `error` / `success` fields. Every `copyWith` clears the
  last two, which is what makes a toast fire once.
- Every user action is a notifier method wrapped in `runAction(...)` — it
  handles loading and `AppException` for you. Do not hand-write
  `try` / `catch` / `state = AsyncError(...)` in a notifier.
- A view draws the notifier with `AppAsyncView` (`shared/widgets/app_async_view.dart`)
  — skeleton, error, empty and body — and reacts to one-shot results with
  `ref.listenAction` (`shared/widgets/feedback/action_listener.dart`). Side
  effects (toasts, navigation, dialogs) go in the listener, never in `build`.
- `ref.watch` in `build`, `ref.read` in callbacks.
''';

  static String _blocRules() => r'''
## State — Bloc

- A feature's state holder is a `Bloc<XEvent, XState>` in
  `presentation/blocs/`, with `ActionBlocMixin` (`core/utils/app_status.dart`).
  Blocs import `package:bloc/bloc.dart`, never Flutter.
- Events are a `sealed` family of `final class`es, one per user action.
- The state is **one** `Equatable` class with an `AppStatus status` field plus
  one-shot `errorMessage` / `successMessage` fields that every `copyWith`
  drops. Do not split it into a sealed class per phase. Every field goes into
  `props`, `copyWith` and the `placeholder` the skeleton draws.
- Every handler runs through `runAction(emit, (current) async { ... })`, which
  handles loading and `AppException`. Do not hand-write
  `try` / `on AppException` in a handler.
- `presentation/pages/<x>_page.dart` creates the bloc with
  `getIt<XBloc>()` in a `BlocProvider`; `views/<x>_view.dart` never touches the
  locator. Routes point at the page.
- The view uses `BlocConsumer`: the `listener` (with `listenWhen` on the two
  message fields) shows toasts and navigates; the `builder` returns
  `AppStatusView` (`shared/widgets/app_status_view.dart`). Side effects never
  go in `builder`.
- Blocs are registered with `registerFactory` in `presentation_module.dart` —
  never as singletons.
- A pushed route, a sheet or a dialog cannot `context.read` the blocs of the
  screen that opened it (they are siblings in the Navigator). Carry them with a
  scope — `moarch create scope <feature> <name>`, then
  `context.show<Name>Sheet(...)` or `extra: <Name>Scope.of(context)` +
  `.provide(child:)` — and never create a second instance of the same bloc.
  For routes nested under a screen, prefer a `ShellRoute` providing the blocs.
''';

  static String _ui({
    required bool withDarkTheme,
    required bool withStatusColors,
  }) =>
      '''
## UI

- Build screens from `lib/shared/widgets/` (`AppButton`, `AppInput`,
  `AppAppBar`, `AppToast`, `ErrorView`, `EmptyView`…) before raw Material
  widgets. `docs/UI_KIT.md` lists the kit; a widget it lists but the project
  lacks is added with `moarch create widget <name>`, not written from scratch.
- No magic numbers: spacing, padding, radii, icon sizes, durations, curves and
  shadows come from `AppConstants` (`space16`, `padding16`, `borderRadius12`,
  `duration300`, `curveStandard`, `shadowCard`…).
- No hard-coded colors: read `Theme.of(context).colorScheme`${withStatusColors ? ', and\n  `context.statusColors` for success / warning / info' : ''}.${withDarkTheme ? ' The app has a dark\n  theme, so a literal `Color` is a bug in one of the two.' : ''}
- A growing `build` is split into private widget **classes** (`_Header`), not
  `Widget _buildHeader()` methods. `const` wherever it compiles.
''';

  static String _addingAFeature({
    required bool bloc,
    required bool withRouter,
  }) =>
      '''
## Adding a feature

1. `moarch create feature <name>` — never create the folders by hand.
2. Fields on `domain/models/<name>_model.dart`, then run `build_runner`.
3. Methods on the repository interface, implemented in the `_impl`, with the
   call itself in the datasource.
4. ${bloc ? 'An event per action, a handler through `runAction`, and the fields on the state\n   (`copyWith`, `props`, `placeholder`).' : 'A notifier method per action through `runAction`, and the fields on the state\n   (`copyWith`).'}
5. The screen in `presentation/views/`, from the UI kit.${withRouter ? '\n6. The path in `lib/config/router/app_routes.dart` and the route in\n   `app_router.dart`${bloc ? ', pointing at the page' : ''}.' : ''}
''';

  static String _localization({required bool easy}) => easy
      ? r'''
## Localization

User-facing strings live in `assets/translations/*.json` (easy_localization)
and are read with `'key'.tr()`. Add every new key to **every** language file.
'''
      : r'''
## Localization

User-facing strings live in `lib/l10n/app_*.arb` (flutter_localizations) and
are read through `AppLocalizations.of(context)`. Add every new key to
**every** `.arb` file; `fvm flutter gen-l10n` regenerates the accessors.
''';

  static String _generated({required bool withAuthFeature}) =>
      '''
## Files moarch owns

`.moarch.yaml` records a hash of every file moarch generated, and
`moarch update` refreshes the ones nobody edited. Editing one of them is
allowed — the edit is kept, and later updates report it for review instead of
overwriting it — but prefer extending over rewriting:

- `lib/core/`, `lib/config/`, `lib/shared/widgets/`${withAuthFeature ? ', `lib/features/auth/`' : ''}
- `README.md`, `AGENTS.md`, `CLAUDE.md`, `docs/`, `analysis_options.yaml`,
  `.github/workflows/`

Never edit `.moarch.yaml`, `*.g.dart` or `*.freezed.dart`.
''';

  static String _done({required bool bloc}) =>
      '''
## Definition of done

A change is finished when all of these pass:

```bash
fvm dart format .
fvm flutter analyze
fvm flutter test
```${bloc ? '\n\nand `bloc lint .` reports nothing new.' : ''}

CI runs the same checks and fails on any of them.
''';
}
