/// The Claude Code mod `init` writes beside the agent skills: a plugin of
/// function hooks in `.claude/skills/moarch-mod/`, which Claude Code loads
/// on its own from a project's skills folder.
///
/// It guards the generated files and the `// moarch:` anchors, tracks the
/// sources build_runner has not caught up with, opens a project dashboard
/// with `/moarch`, and declares a haiku `runner` agent for long-output
/// checks. Claude Code only: every other agent reads AGENTS.md and the
/// skills, which say the same rules in words.
///
/// The files are TypeScript and are not checked by `dart test`. After
/// changing one, generate a project and run `claude plugin validate` and
/// `claude plugin test` on its `.claude/skills/moarch-mod/`.
class ClaudeModTemplates {
  ClaudeModTemplates._();

  /// The folder the mod lives in, project-relative.
  static const dir = '.claude/skills/moarch-mod';

  /// Every file of the mod, in the order `init` writes them.
  static const all = <ClaudeModFile>[
    ClaudeModFile(
      slug: 'claude-mod-manifest',
      path: '$dir/.claude-plugin/plugin.json',
      title: 'Claude Code mod manifest',
      description:
          "The mod's name and description, which Claude Code lists it by.",
      content: _manifest,
    ),
    ClaudeModFile(
      slug: 'claude-mod-hooks',
      path: '$dir/hooks/hooks.json',
      title: 'Claude Code mod hooks list',
      description: 'Points Claude Code at the hooks module.',
      content: _hooks,
    ),
    ClaudeModFile(
      slug: 'claude-mod-register',
      path: '$dir/hooks/register.tsx',
      title: 'Claude Code mod hooks',
      description:
          'The guards, the build_runner tracking and the /moarch pane.',
      content: _register,
    ),
    ClaudeModFile(
      slug: 'claude-mod-rules',
      path: '$dir/hooks/rules.ts',
      title: 'Claude Code mod rules',
      description:
          'What the hooks check: generated files, anchors, the manifest hash.',
      content: _rules,
    ),
    ClaudeModFile(
      slug: 'claude-mod-types',
      path: '$dir/types/index.d.ts',
      title: 'Claude Code mod state types',
      description: 'The values the mod keeps for the session.',
      content: _types,
    ),
    ClaudeModFile(
      slug: 'claude-mod-runner',
      path: '$dir/agents/runner.md',
      title: 'Claude Code runner agent',
      description:
          'A haiku subagent that runs the checks and reports only what failed.',
      content: _runner,
    ),
    ClaudeModFile(
      slug: 'claude-mod-tsconfig',
      path: '$dir/tsconfig.json',
      title: 'Claude Code mod tsconfig',
      description:
          'Type-checks the mod against the types Claude Code lays beside it.',
      content: _tsconfig,
    ),
    ClaudeModFile(
      slug: 'claude-mod-test-rules',
      path: '$dir/tests/rules.test.ts',
      title: 'Claude Code mod rules tests',
      description: "`claude plugin test`'s checks of rules.ts.",
      content: _testRules,
    ),
    ClaudeModFile(
      slug: 'claude-mod-test-guard',
      path: '$dir/tests/guard.test.ts',
      title: 'Claude Code mod guard tests',
      description: "`claude plugin test`'s checks of the guards and tracking.",
      content: _testGuard,
    ),
    ClaudeModFile(
      slug: 'claude-mod-test-dashboard',
      path: '$dir/tests/dashboard.test.tsx',
      title: 'Claude Code mod pane tests',
      description: "`claude plugin test`'s checks of the /moarch pane.",
      content: _testDashboard,
    ),
  ];

  /// The file `ScaffoldContext.hasClaudeMod` looks for.
  static String get markerPath => '$dir/hooks/register.tsx';

  static const _manifest = r'''
{
  "name": "moarch-mod",
  "version": "1.0.0",
  "description": "Claude Code mod for this moarch project: guards generated files and moarch anchors, tracks pending build_runner runs, and opens a project dashboard with /moarch.",
  "author": { "name": "moarch" },
  "types": "./types/index.d.ts"
}
''';

  static const _hooks = r'''
{ "modules": ["./register.tsx"] }
''';

  static const _register = r'''
// Generated by moarch. Claude Code loads this folder as a mod (a plugin of
// function hooks) because it sits in .claude/skills/. The rules it enforces
// are in rules.ts; `claude plugin test .claude/skills/moarch-mod` runs tests/.
import { atom, read, update } from 'claude-code'
import type { EngineInterface, Register } from 'claude-code'

import type { MoarchModDashboard } from '../types'
import {
  droppedAnchors,
  hashContent,
  needsCodegen,
  parseManifest,
  relativeTo,
  runsCodegen,
  slashes,
  sourceOf,
  stackOf,
} from './rules'

const PANE = 'moarch'
const CODEGEN = 'fvm dart run build_runner build -d'
const pending = atom({ plugin: 'moarch-mod', key: 'pending' } as const, [])
const dashboard = atom({ plugin: 'moarch-mod', key: 'dashboard' } as const, null)

async function readOr($: EngineInterface, path: string): Promise<string | undefined> {
  try {
    return await $.fs.read(path)
  } catch {
    return undefined
  }
}

/** Puts the pending build_runner run on the status line, or clears it. */
function showPending($: EngineInterface, files: string[]): void {
  $.ui.status(files.length === 0 ? undefined : `build_runner pending (${files.length})`)
}

/** Why an edit to [path] is refused: it is build_runner's output. */
async function generatedDeny($: EngineInterface, path: string, source: string): Promise<{ deny: string }> {
  const root = await $.session.root()

  return {
    deny: `${relativeTo(root, path)} is generated by build_runner. Edit ${relativeTo(root, source)} instead, then run ${CODEGEN}.`,
  }
}

/** Records [path] as needing build_runner when its new text has a generated `part`. */
async function track($: EngineInterface, path: string): Promise<void> {
  const text = await readOr($, path)
  if (text === undefined || !needsCodegen(path, text)) {
    return
  }

  const file = relativeTo(await $.session.root(), path)
  const before = await read($, pending)
  if (before.includes(file)) {
    return
  }

  const files = await update($, pending, list => [...list, file])
  showPending($, files)
  if (before.length === 0) {
    $.ui.toast(`${file} has generated parts: run ${CODEGEN}`)
  }
}

/** Reads the project into the dashboard: stack, features and drift from .moarch.yaml. */
async function inspect($: EngineInterface): Promise<MoarchModDashboard> {
  const pubspec = (await readOr($, 'pubspec.yaml')) ?? ''
  const manifest = parseManifest((await readOr($, '.moarch.yaml')) ?? '')
  let features: string[] = []
  try {
    features = (await $.fs.list('lib/features'))
      .filter(entry => entry.kind === 'dir')
      .map(entry => entry.name)
      .sort()
  } catch {
    features = []
  }

  const edited: string[] = []
  const missing: string[] = []
  for (const [path, hash] of Object.entries(manifest.files)) {
    const text = await readOr($, path)
    if (text === undefined) missing.push(path)
    else if (hashContent(text) !== hash) edited.push(path)
  }

  const found: MoarchModDashboard = {
    project: /^name:\s*(\S+)/m.exec(pubspec)?.[1] ?? '?',
    stack: stackOf(pubspec),
    features,
    edited,
    missing,
    tracked: Object.keys(manifest.files).length,
  }
  if (manifest.version !== undefined) {
    found.moarchVersion = manifest.version
  }

  return found
}

async function refresh($: EngineInterface): Promise<void> {
  const found = await inspect($)
  await update($, dashboard, () => found)
}

async function costOf($: EngineInterface): Promise<string> {
  try {
    const usage = await $.session.usage()

    return usage.cost === undefined ? 'n/a' : `$${usage.cost.usd.toFixed(2)}`
  } catch {
    return 'n/a'
  }
}

export const register: Register = on => {
  on('session.start', async ($, e, next) => {
    await $.command.register({
      name: 'moarch',
      description: 'Show this project: stack, features, edited moarch files, pending build_runner',
    })
    showPending($, await read($, pending))

    return next(e)
  })

  on('command.run', { command: 'moarch' }, async $ => {
    await refresh($)
    await $.ui.open({ id: PANE, title: 'moarch' })

    return { text: 'moarch pane opened.' }
  })

  // Generated files are rewritten by build_runner, and the anchors are where
  // `moarch create` inserts registrations, routes and endpoints. A guard that
  // fails lets the edit through rather than block work.
  on('tool.call', { tool: 'Edit' }, async ($, e, next) => {
    const source = sourceOf(slashes(e.file_path))
    if (source !== undefined) {
      return generatedDeny($, e.file_path, source)
    }
    const dropped = droppedAnchors(e.old_string, e.new_string)
    if (dropped.length > 0) {
      return { deny: `This edit removes ${dropped.join(', ')}. moarch inserts new code above that line: keep it.` }
    }

    const ran = await next(e)
    if (ran.deny === undefined && ran.isError !== true) await track($, e.file_path)

    return ran
  }).catch(($, e, next) => next(e))

  on('tool.call', { tool: 'Write' }, async ($, e, next) => {
    const source = sourceOf(slashes(e.file_path))
    if (source !== undefined) {
      return generatedDeny($, e.file_path, source)
    }
    const before = await readOr($, e.file_path)
    const dropped = before === undefined ? [] : droppedAnchors(before, e.content)
    if (dropped.length > 0) {
      return { deny: `This rewrite drops ${dropped.join(', ')}. moarch inserts new code above that line: keep it.` }
    }

    const ran = await next(e)
    if (ran.deny === undefined && ran.isError !== true) await track($, e.file_path)

    return ran
  }).catch(($, e, next) => next(e))

  on('tool.call', { tool: 'Bash' }, async ($, e, next) => {
    const ran = await next(e)
    if (runsCodegen(e.command) && ran.deny === undefined && ran.isError !== true) {
      showPending($, await update($, pending, () => []))
    }

    return ran
  })

  on('ui.render', { component: 'Pane', requestId: PANE }, async ($, e) => {
    const { Box, Button, Text } = $.ui.resolve(e)
    const now = await read($, dashboard)
    const waiting = await read($, pending)
    const cost = await costOf($)

    if (now === null) {
      return <Text dimColor>Reading the project…</Text>
    }

    const drift = [...now.edited.map(path => `edited  ${path}`), ...now.missing.map(path => `deleted ${path}`)]

    return (
      <Box flexDirection="column">
        <Text bold>
          {now.project} · {now.stack}
          {now.moarchVersion === undefined ? '' : ` · moarch ${now.moarchVersion}`}
        </Text>
        <Text dimColor>Session cost {cost}</Text>
        <Text> </Text>
        <Text bold>Features ({now.features.length})</Text>
        <Text>{now.features.length === 0 ? '  none yet: moarch create feature <name>' : `  ${now.features.join(', ')}`}</Text>
        <Text> </Text>
        <Text bold>build_runner</Text>
        {waiting.length === 0 ? (
          <Text color="success">  ✓ Nothing pending</Text>
        ) : (
          <Box flexDirection="column">
            <Text color="warning">  ! {waiting.length} source(s) changed since the last run: {CODEGEN}</Text>
            {waiting.slice(0, 8).map(path => (
              <Text dimColor>    {path}</Text>
            ))}
          </Box>
        )}
        <Text> </Text>
        <Text bold>Generated files ({now.tracked} tracked in .moarch.yaml)</Text>
        {now.tracked === 0 && <Text dimColor>  No .moarch.yaml: moarch update treats every file as edited.</Text>}
        {now.tracked > 0 && drift.length === 0 && <Text color="success">  ✓ All as moarch wrote them: moarch update refreshes them all</Text>}
        {drift.length > 0 && (
          <Box flexDirection="column">
            <Text color="warning">  ! {drift.length} changed: moarch update skips these without --force</Text>
            {drift.slice(0, 12).map(line => (
              <Text dimColor>    {line}</Text>
            ))}
            {drift.length > 12 && <Text dimColor>    and {drift.length - 12} more</Text>}
          </Box>
        )}
        <Text> </Text>
        <Box>
          <Button key="refresh" label="Refresh" onPress={() => refresh($)} />
        </Box>
      </Box>
    )
  })
}
''';

  static const _rules = r'''
// The project rules the hooks enforce, kept free of `$` so tests/ can call
// them directly.

const GENERATED = /\.(g|freezed)\.dart$/
const PART = /^part\s+'[^']+\.(g|freezed)\.dart'\s*;/m
const ANCHOR = /\/\/ moarch:[a-z_]+/g

/** Forward slashes, so a Windows path reads like the manifest's keys. */
export function slashes(path: string): string {
  return path.replace(/\\/g, '/')
}

/** [path] relative to [root] when it lies under it, else [path] as given. */
export function relativeTo(root: string, path: string): string {
  const base = slashes(root).replace(/\/$/, '')
  const full = slashes(path)

  return full.toLowerCase().startsWith(`${base.toLowerCase()}/`)
    ? full.slice(base.length + 1)
    : full
}

/** The source build_runner writes [path] from, or undefined when [path] is not generated. */
export function sourceOf(path: string): string | undefined {
  return GENERATED.test(path) ? path.replace(GENERATED, '.dart') : undefined
}

/** Whether [path], with [text] in it, has a `part` build_runner writes. */
export function needsCodegen(path: string, text: string): boolean {
  return path.endsWith('.dart') && !GENERATED.test(path) && PART.test(text)
}

/** The moarch anchors (`// moarch:routes`, ...) [before] has and [after] lost. */
export function droppedAnchors(before: string, after: string): string[] {
  const kept = new Set(after.match(ANCHOR) ?? [])

  return [...new Set(before.match(ANCHOR) ?? [])].filter(anchor => !kept.has(anchor))
}

/** Whether a shell command runs build_runner. */
export function runsCodegen(command: string): boolean {
  return /build_runner\s+(build|watch)/.test(command)
}

/**
 * The hash `.moarch.yaml` records: FNV-1a (64-bit) over the UTF-8 bytes with
 * CRLF read as LF, carried in two 32-bit halves as moarch's own Dart does.
 */
export function hashContent(content: string): string {
  const bytes = new TextEncoder().encode(content.replace(/\r\n/g, '\n'))
  const word = 0x100000000
  let hi = 0xcbf29ce4
  let lo = 0x84222325
  for (const byte of bytes) {
    lo = (lo ^ byte) >>> 0
    const l = lo * 0x1b3
    const h = hi * 0x1b3 + lo + Math.floor(l / word)
    lo = l % word
    hi = h % word
  }

  return hi.toString(16).padStart(8, '0') + lo.toString(16).padStart(8, '0')
}

/** The version and file hashes in `.moarch.yaml`. */
export function parseManifest(text: string): { version?: string; files: Record<string, string> } {
  const version = /^version:\s*'?([^'\s]+)'?/m.exec(text)?.[1]
  const files: Record<string, string> = {}
  for (const match of text.matchAll(/^\s+'([^']+)':\s*'([0-9a-f]{16})'/gm)) {
    files[match[1]!] = match[2]!
  }

  return { version, files }
}

/** `bloc` or `riverpod`, from the dependencies in pubspec.yaml. */
export function stackOf(pubspec: string): string {
  if (/^\s+flutter_bloc:/m.test(pubspec)) return 'bloc'
  if (/^\s+(flutter_riverpod|hooks_riverpod):/m.test(pubspec)) return 'riverpod'

  return 'unknown'
}
''';

  static const _types = r'''
/** What the /moarch pane draws, read off the project when it opens or refreshes. */
export type MoarchModDashboard = {
  /** `name:` in pubspec.yaml. */
  project: string
  /** `riverpod` or `bloc`, from the pubspec's dependencies. */
  stack: string
  /** The moarch version that last wrote `.moarch.yaml`; absent without one. */
  moarchVersion?: string
  /** The folders under lib/features/. */
  features: string[]
  /** Files `.moarch.yaml` records whose content changed: `moarch update` skips them. */
  edited: string[]
  /** Files `.moarch.yaml` records that are no longer on disk. */
  missing: string[]
  /** How many files `.moarch.yaml` records. */
  tracked: number
}

declare module 'claude-code' {
  interface PluginState {
    'moarch-mod': {
      /** Project-relative sources edited since build_runner last ran. */
      pending: string[]
      dashboard: MoarchModDashboard | null
    }
  }
}
''';

  static const _runner = r'''
---
name: runner
description: Runs this project's checks and generators (fvm flutter analyze/test, fvm dart format, build_runner, moarch create/update/doctor) and reports only what failed. Use it for any command with long output, so the main conversation gets the result instead of the log.
tools: Bash, Read, Grep, Glob
model: haiku
---

You run commands in a Flutter project scaffolded by moarch and report what
happened. You do not edit files.

- Run exactly the commands you are given, from the project root. Flutter and
  Dart are pinned with FVM: use `fvm flutter …` and `fvm dart …`.
- When a command passes, say so in one line.
- When it fails, list each problem as `path:line: message`, at most 20, and
  the count of any you left out. Quote the failing test's name and its
  expectation, not the whole stack trace.
- For `moarch` commands, list the files written, skipped and refused.
- Never fix anything, rerun with different flags, or guess at a cause. The
  agent that called you decides what to do next.
''';

  static const _tsconfig = r'''
{
  "compilerOptions": {
    "target": "es2023",
    "lib": ["es2023"],
    "types": [],
    "module": "esnext",
    "moduleResolution": "bundler",
    "strict": true,
    "noUncheckedIndexedAccess": true,
    "noEmit": true,
    "skipLibCheck": true,
    "jsx": "react",
    "jsxFactory": "h",
    "jsxFragmentFactory": "Fragment"
  },
  "include": [".claude-plugin/types", "hooks", "types", "tests"]
}
''';

  static const _testRules = r'''
import { describe, expect, test } from 'claude-code/testing'

import {
  droppedAnchors,
  hashContent,
  needsCodegen,
  parseManifest,
  relativeTo,
  runsCodegen,
  sourceOf,
  stackOf,
} from '../hooks/rules'

describe('rules', () => {
  test('hashes as .moarch.yaml does', async () => {
    expect(hashContent('')).toBe('cbf29ce484222325')
    expect(hashContent('hello\r\nworld\n')).toBe('4ff9450a10388969')
    expect(hashContent("part 'user.g.dart';\nclass Café {}\n")).toBe('5c57d3c219f29e74')
  })

  test('maps a generated file to its source', async () => {
    expect(sourceOf('lib/features/user/domain/models/user.freezed.dart')).toBe(
      'lib/features/user/domain/models/user.dart',
    )
    expect(sourceOf('lib/config/env/env.g.dart')).toBe('lib/config/env/env.dart')
    expect(sourceOf('lib/main.dart')).toBeUndefined()
  })

  test('needs build_runner only for a source with generated parts', async () => {
    expect(needsCodegen('lib/user.dart', "part 'user.freezed.dart';\npart 'user.g.dart';")).toBe(true)
    expect(needsCodegen('lib/main.dart', "import 'app.dart';")).toBe(false)
    expect(needsCodegen('lib/user.g.dart', "part of 'user.dart';")).toBe(false)
  })

  test('finds the anchors an edit removes', async () => {
    const before = '  // moarch:routes\n  // moarch:registrations\n'
    expect(droppedAnchors(before, '  // moarch:routes\n')).toEqual(['// moarch:registrations'])
    expect(droppedAnchors(before, `GoRoute(),\n${before}`)).toEqual([])
  })

  test('reads the manifest', async () => {
    const manifest = parseManifest(
      "version: '9.8.0'\ngenerated_at: 'x'\nstack: []\nfiles:\n  'lib/main.dart': 'cbf29ce484222325'\n",
    )
    expect(manifest.version).toBe('9.8.0')
    expect(manifest.files).toEqual({ 'lib/main.dart': 'cbf29ce484222325' })
  })

  test('reads paths, commands and the stack', async () => {
    expect(relativeTo('C:\\work\\app', 'C:\\work\\app\\lib\\main.dart')).toBe('lib/main.dart')
    expect(relativeTo('/work/app/', '/elsewhere/a.dart')).toBe('/elsewhere/a.dart')
    expect(runsCodegen('fvm dart run build_runner build -d')).toBe(true)
    expect(runsCodegen('fvm flutter test')).toBe(false)
    expect(stackOf('dependencies:\n  flutter_bloc: ^9.0.0\n')).toBe('bloc')
    expect(stackOf('dependencies:\n  flutter_riverpod: ^3.0.0\n')).toBe('riverpod')
  })
})
''';

  static const _testGuard = r'''
import type { On } from 'claude-code'
import { expect, test } from 'claude-code/testing'

const ROOT = '/work/app'
const ROUTER = `${ROOT}/lib/config/router/app_router.dart`
const MODEL = `${ROOT}/lib/features/user/domain/models/user.dart`
const FILES: Record<string, string> = {
  'lib/config/router/app_router.dart': 'routes: [\n  // moarch:routes\n]\n',
  'lib/features/user/domain/models/user.dart': "part 'user.freezed.dart';\n",
}

/** Answers what the engine would, and records the status line in [statuses]. */
function engine(on: On, statuses: (string | undefined)[]): void {
  on('session.root', () => ({ value: ROOT }))
  on('fs.read', ($, e) => {
    const path = Object.keys(FILES).find(name => e.path.replace(/\\/g, '/').endsWith(name))
    if (path === undefined) throw new Error(`ENOENT ${e.path}`)

    return { value: FILES[path]! }
  })
  on('ui.status', ($, e) => {
    statuses.push(e.text)

    return { value: undefined }
  })
  on('ui.toast', () => ({ value: undefined }))
  on('tool.call', () => ({ result: { ok: true } }))
}

test('refuses edits to generated files and removed anchors', async ($, on) => {
  engine(on, [])

  const generated = await $.tool.call({
    tool: 'Edit',
    file_path: `${ROOT}/lib/features/user/domain/models/user.freezed.dart`,
    old_string: 'a',
    new_string: 'b',
  })
  expect(generated.deny).toContain('Edit lib/features/user/domain/models/user.dart instead')

  const anchor = await $.tool.call({ tool: 'Write', file_path: ROUTER, content: 'routes: []\n' })
  expect(anchor.deny).toContain('// moarch:routes')

  const kept = await $.tool.call({
    tool: 'Edit',
    file_path: ROUTER,
    old_string: '  // moarch:routes',
    new_string: '  GoRoute(),\n  // moarch:routes',
  })
  expect(kept.deny).toBeUndefined()
})

test('shows a model edit as pending until build_runner runs', async ($, on) => {
  const statuses: (string | undefined)[] = []
  engine(on, statuses)

  await $.tool.call({ tool: 'Edit', file_path: MODEL, old_string: 'a', new_string: 'b' })
  expect(statuses.at(-1)).toBe('build_runner pending (1)')

  await $.tool.call({ tool: 'Bash', command: 'fvm dart run build_runner build -d' })
  expect(statuses.at(-1)).toBeUndefined()
})
''';

  static const _testDashboard = r'''
import { expect, test } from 'claude-code/testing'

import { hashContent } from '../hooks/rules'

const MAIN = 'void main() {}\n'
const FILES: Record<string, string> = {
  'pubspec.yaml': 'name: shop\ndependencies:\n  flutter_riverpod: ^3.0.0\n',
  '.moarch.yaml': [
    "version: '9.8.0'",
    'files:',
    `  'lib/main.dart': '${hashContent(MAIN)}'`,
    `  'lib/config/theme/app_theme.dart': '${hashContent('as generated')}'`,
    `  'lib/config/router/app_router.dart': '${hashContent('gone')}'`,
    '',
  ].join('\n'),
  'lib/main.dart': MAIN,
  'lib/config/theme/app_theme.dart': 'as edited by the team',
}

const PANE = {
  title: 'moarch',
  isFocused: true,
  bodyColumns: 100,
  placement: 'dock',
  scroll: { offset: 0, bodyRows: 40 },
  view: {},
} as const

test('the pane shows the stack, features and edited files', async ($, on) => {
  on('fs.read', ($, e) => {
    const path = Object.keys(FILES).find(name => e.path.replace(/\\/g, '/').endsWith(name))
    if (path === undefined) throw new Error(`ENOENT ${e.path}`)

    return { value: FILES[path]! }
  })
  on('fs.list', () => ({
    value: [
      { name: 'cart', kind: 'dir', size: 0, mtimeMs: 0, isLink: false },
      { name: 'auth', kind: 'dir', size: 0, mtimeMs: 0, isLink: false },
    ],
  }))
  on('ui.open', () => ({ value: { isPlaced: true } }))
  on('ui.render', ($, e) => {
    const { Box } = $.ui.resolve(e)

    return <Box />
  })

  await $.command.run({
    command: 'moarch',
    args: '',
    origin: { kind: 'composer' },
    presentation: { isFullscreen: false, columns: 120 },
  })

  for (const surface of ['terminal', 'desktop'] as const) {
    const ui = await $.ui.mount({ plugin: 'moarch-mod', surface, component: 'Pane', requestId: 'moarch', props: PANE })
    expect(await ui.find({ type: 'Text', text: 'shop · riverpod · moarch 9.8.0' })).toBeDefined()
    expect(await ui.find({ type: 'Text', text: 'auth, cart' })).toBeDefined()
    expect(await ui.find({ type: 'Text', text: '2 changed' })).toBeDefined()
    expect(await ui.find({ type: 'Text', text: 'edited  lib/config/theme/app_theme.dart' })).toBeDefined()
    expect(await ui.find({ type: 'Text', text: 'deleted lib/config/router/app_router.dart' })).toBeDefined()
    await ui.unmount()
  }
})
''';
}

/// One file of the Claude Code mod.
class ClaudeModFile {
  /// Creates a file entry.
  const ClaudeModFile({
    required this.slug,
    required this.path,
    required this.title,
    required this.description,
    required this.content,
  });

  /// The catalog slug `moarch update` takes.
  final String slug;

  /// Where it lands, project-relative with forward slashes.
  final String path;

  /// What `moarch update --list` calls it.
  final String title;

  /// One line on what it is for.
  final String description;

  /// The file's content.
  final String content;
}
