import '../../utils/state_management.dart';

/// The project README `moarch init` writes at the project root.
///
/// The other documents under `docs/` are task lists — this is the one aimed at
/// a person: what the project is, how to run it the first time, what each
/// layer is for, how the chosen state stack works, and where `docs/` picks up.
/// It is written for someone who has never touched a Clean Architecture
/// Flutter app, so it explains the reasoning and not only the commands.
///
/// Every section is built from what the project actually has — the stack, the
/// packages, the flavors — so nothing here describes a file that was never
/// generated. The two placeholder sections (the owner line and
/// **Contacts & access**) are the exception: they are `[bracketed]` prompts
/// for the team to fill in, since no amount of detection can know them.
class ReadmeTemplates {
  ReadmeTemplates._();

  /// Returns the README for a project.
  ///
  /// [flavors] is the flavor set read off `flavorizr.yaml`; empty means the
  /// project has not run `moarch create flavors` yet, and the flavors section
  /// becomes the setup walkthrough instead of the per-flavor build commands.
  static String projectReadme({
    required String projectName,
    required StateManagement stateManagement,
    List<String> flavors = const [],
    bool withDio = false,
    bool withRouter = false,
    bool withAuthFeature = false,
    bool withFirebaseAuthFeature = false,
    bool withFirebase = false,
    bool withFirestore = false,
    bool withCrashlytics = false,
    bool withFirebaseNotifications = false,
    bool withNotifications = false,
    bool withLocalization = false,
    bool withEasyLocalization = false,
    bool withBiometric = false,
    bool withDarkTheme = false,
    bool withWorkflows = false,
  }) {
    final bloc = stateManagement.isBloc;
    return <String>[
      _header(projectName, bloc: bloc),
      _overview(bloc: bloc, withRouter: withRouter, withDio: withDio),
      _gettingStarted(
        flavors: flavors,
        withDio: withDio,
        withFirebase: withFirebase,
        withLocalization: withLocalization,
      ),
      _techStack(
        bloc: bloc,
        withDio: withDio,
        withRouter: withRouter,
        withFirebase: withFirebase,
        withFirestore: withFirestore,
        withCrashlytics: withCrashlytics,
        withFirebaseNotifications: withFirebaseNotifications,
        withNotifications: withNotifications,
        withLocalization: withLocalization,
        withEasyLocalization: withEasyLocalization,
        withBiometric: withBiometric,
        withFirebaseAuthFeature: withFirebaseAuthFeature,
        withFlavors: flavors.isNotEmpty,
      ),
      _structure(
        bloc: bloc,
        withRouter: withRouter,
        withAuthFeature: withAuthFeature,
        withFirebase: withFirebase,
        withFlavors: flavors.isNotEmpty,
        withLocalization: withLocalization || withEasyLocalization,
      ),
      _architecture(bloc: bloc, withDio: withDio),
      bloc ? _blocGuide() : _riverpodGuide(),
      _addingAFeature(bloc: bloc, withRouter: withRouter),
      _flavorsSection(
        flavors: flavors,
        projectName: projectName,
        withFirebase: withFirebase,
      ),
      _building(flavors: flavors),
      _cicd(withWorkflows: withWorkflows, withFirebase: withFirebase),
      _standards(bloc: bloc, withDarkTheme: withDarkTheme),
      _contacts(withFirebase: withFirebase),
      _links(
        bloc: bloc,
        withDio: withDio,
        withRouter: withRouter,
        withFirebase: withFirebase,
        withLocalization: withLocalization,
        withEasyLocalization: withEasyLocalization,
        withBiometric: withBiometric,
      ),
      _footer,
      // Each section ends with its own `---` rule and no trailing blank line;
      // joining on one puts the blank line between the rule and the next
      // heading, which is what keeps the markdown readable in a plain editor.
    ].join('\n');
  }

  /// The title block and table of contents.
  static String _header(String projectName, {required bool bloc}) => '''
# 📱 $projectName

> **Last updated:** `[month year]`
> **Owner:** `[name]`
> **Primary platform:** Flutter (iOS & Android)
> **Architecture:** Clean Architecture + ${bloc ? 'flutter_bloc' : 'Riverpod'} + get_it

This is the guide to the project: what it is, how to get it running, how it is
put together and how it ships. It assumes no prior experience with this
codebase or with Clean Architecture — read it top to bottom the first time,
then use it as a reference.

The scaffolding was generated by [moarch](https://pub.dev/packages/moarch);
everything below describes **this** project, not the generator.

---

## Table of Contents

1. [What this project is](#1-what-this-project-is)
2. [Getting started](#2-getting-started)
3. [Tech stack & tools](#3-tech-stack--tools)
4. [Project structure](#4-project-structure)
5. [How the architecture works](#5-how-the-architecture-works)
6. [State management — ${bloc ? 'Bloc' : 'Riverpod'}](#6-state-management--${bloc ? 'bloc' : 'riverpod'})
7. [Adding a feature](#7-adding-a-feature)
8. [Flavors & environments](#8-flavors--environments)
9. [Building the app](#9-building-the-app)
10. [CI/CD & GitHub secrets](#10-cicd--github-secrets)
11. [Code standards](#11-code-standards)
12. [Contacts & access](#12-contacts--access)
13. [Documentation & links](#13-documentation--links)

---
''';

  /// Section 1 — the one-screen explanation of what the app is and why the
  /// folders look the way they do.
  static String _overview({
    required bool bloc,
    required bool withRouter,
    required bool withDio,
  }) =>
      '''
## 1. What this project is

A **Flutter** application targeting **iOS** and **Android** from a single Dart
codebase. Everything — screens, business rules, API calls — lives in `lib/`.
The `android/` and `ios/` folders are the native shells Flutter builds into;
you will only open them for signing, permissions and platform configuration.

The code follows **Clean Architecture**. That is one idea, applied per feature:

> Business rules must not depend on the things that come and go —
> the UI framework, the HTTP client, the database.

So each feature is split into three layers, and the dependencies only ever
point *inwards*, towards the rules:

| Layer | What lives there | May import |
|---|---|---|
| `domain` | Entities (plain Dart objects) and repository **interfaces** — the rules, and the promises the app makes | nothing but Dart |
| `data` | Models (JSON in / JSON out), datasources${withDio ? ' (Dio, secure storage)' : ''}, and the repository **implementations** | `domain` |
| `presentation` | Screens and the ${bloc ? 'blocs' : 'notifiers'} that hold their state | `domain` |

```
presentation ─────► domain ◄───── data
     (UI)         (the rules)    (the world)
```

`presentation` never imports `data`. It asks the `domain` interface for what it
needs, and the wiring in `lib/config/di/injector.dart` decides which
implementation answers. That indirection is what makes the data layer
replaceable${withDio ? ' — swapping REST for something else touches `data/` only' : ''}, and what makes the rules testable
without a device.

**Why it is worth the extra folders:** a screen that talks to Dio directly
cannot be tested without a network, cannot be reused when the endpoint changes,
and spreads error handling across the UI. Three folders up front avoid all
three.

### Generated, and still refreshable

The scaffold recorded a hash of every file it wrote in `.moarch.yaml`. That
lets the generator tell an untouched file from one you edited:

```bash
moarch update --list   # what is out of date, and what you have edited
moarch update <name>   # refresh a file you never touched
moarch doctor          # check the project for known problems
```

Files you have edited are **never** overwritten without `--force`. Editing
generated code is expected — it is your code from the moment it lands.

---
''';

  /// Section 2 — the first-run walkthrough. Ordered, because step 4 is the one
  /// that turns "it does not compile" into a five-minute problem.
  static String _gettingStarted({
    required List<String> flavors,
    required bool withDio,
    required bool withFirebase,
    required bool withLocalization,
  }) {
    final runFlavor = flavors.isEmpty ? '' : ' --flavor ${flavors.first}';
    return '''
## 2. Getting started

Do this once, in order. Steps 1 and 4 are the two people skip, and then spend
an afternoon on.

### Prerequisites

| You need | Why |
|---|---|
| Git | to clone the repository |
| Homebrew *or* the Dart SDK | only to install FVM, in step 1 |
| Xcode (macOS only) | to build and run on iOS |
| Android Studio | for the Android SDK and an emulator |

### 1. Install FVM, then the pinned Flutter

This project does not run on "whatever Flutter you happen to have". The exact
version is pinned in `.fvmrc`, and **FVM** (Flutter Version Manager) installs
and selects it.

```bash
# macOS / Linux
brew tap leoafarias/fvm && brew install fvm

# any platform, if you already have the Dart SDK
dart pub global activate fvm
```

Then, from the project root:

```bash
fvm install   # downloads the exact version .fvmrc names
fvm use       # links it into .fvm/flutter_sdk
```

From here on **every** Flutter and Dart command is prefixed with `fvm`:

```bash
fvm flutter --version   # this project's Flutter
flutter --version       # whatever is on your PATH — not necessarily the same
```

That prefix is the whole point. A build that works on your machine and fails in
CI is, more often than anything else, two different Flutter versions.
`.vscode/settings.json` already points the Dart extension at
`.fvm/flutter_sdk`, so once `fvm use` has run, F5, hot reload and the analyzer
use the pinned SDK too. `.fvm/` is gitignored, so a fresh clone has to run
`fvm use` once before that path exists.

### 2. Install the dependencies

```bash
fvm flutter pub get
```

### 3. Create your `.env`

Environment values are not committed. `.env.example` is — copy it and fill it
in:

```bash
cp .env.example .env      # Windows: copy .env.example .env
```

${withDio ? '`BASE_URL` is the API this app talks to. Ask the team for the value of the\nenvironment you are working against.\n' : 'Fill in the keys it lists.\n'}
`.env` is gitignored; `.env.example` is not. Never put a real value in the
example file — add a blank key there whenever you add one to `.env`, so the
next person knows it exists at all.

### 4. Run code generation

`lib/config/env/app_env.dart` does not read `.env` at runtime. The values are
compiled in by **envied**, through `build_runner`:

```bash
fvm dart run build_runner build --delete-conflicting-outputs
```

Run it again whenever `.env` or `app_env.dart` changes. Until it has run once,
`app_env.g.dart` does not exist and the app will not compile.

### 5. Run the app

```bash
fvm flutter devices        # what you can run on
fvm flutter run$runFlavor
```

In VS Code use **Run & Debug** instead — `.vscode/launch.json` already has the
configurations (`debug`, `profile`, `release`${flavors.isEmpty ? '' : ', and one per flavor'}).

### When something goes wrong

| Symptom | Fix |
|---|---|
| `app_env.g.dart` not found | you skipped step 4 |
| build_runner: "conflicting outputs" | re-run it with `--delete-conflicting-outputs` |
| iOS build fails on pods | `cd ios && pod install && cd ..` |
| The analyzer flags things `fvm flutter analyze` does not | run `fvm use`, then reload the window |
| Anything stale or inexplicable | `fvm flutter clean && fvm flutter pub get` |${withFirebase ? '\n| Firebase errors on startup | the console side is not done — see `docs/FIREBASE_SETUP.md` |' : ''}${withLocalization ? '\n| `AppLocalizations` not found | `fvm flutter gen-l10n` |' : ''}
| A generated file looks wrong | `moarch update --list`, then `moarch update <name>` |

---
''';
  }

  /// Section 3 — the tooling table, then the packages that actually shape how
  /// the code is written. Deliberately curated: `pubspec.yaml` is the full
  /// list, and a README that repeats it goes stale on the next `pub add`.
  static String _techStack({
    required bool bloc,
    required bool withDio,
    required bool withRouter,
    required bool withFirebase,
    required bool withFirestore,
    required bool withCrashlytics,
    required bool withFirebaseNotifications,
    required bool withNotifications,
    required bool withLocalization,
    required bool withEasyLocalization,
    required bool withBiometric,
    required bool withFirebaseAuthFeature,
    required bool withFlavors,
  }) {
    final packages = StringBuffer();
    void row(String name, String what) => packages
        .writeln('| [`$name`](https://pub.dev/packages/$name) | $what |');

    if (bloc) {
      row('flutter_bloc', 'State management — see section 6.');
      row('bloc', 'The pure-Dart half, so blocs import no Flutter.');
      row('equatable',
          'Value equality on states and events. Without it every emit repaints.');
    } else {
      row('flutter_riverpod', 'State management — see section 6.');
    }
    row('get_it',
        'The service locator. Repositories and services are registered in `lib/config/di/injector.dart` and read back with `getIt<T>()`.');
    row('envied',
        'Compiles `.env` values into `app_env.dart` instead of shipping the file.');
    if (withDio) {
      row('dio',
          'The HTTP client. Configured in `lib/core/network/dio_client.dart`.');
      row('dio_smart_retry', 'Retries failed requests on transient errors.');
    }
    row('flutter_secure_storage',
        'Keychain / Keystore-backed storage — where tokens go, never `SharedPreferences`.');
    if (withRouter) {
      row('go_router',
          'Declarative routing with an auth-aware redirect — `lib/config/router/`.');
    }
    row('connectivity_plus', 'Detects the device being offline.');
    row('logger',
        'Structured logging — wrapped by `lib/core/utils/app_logger.dart`.');
    row('skeletonizer',
        'Turns a laid-out screen into its own loading skeleton.');
    row('intl', 'Date, number and currency formatting.');
    row('permission_handler', 'Runtime permission requests.');
    row('flutter_native_splash', 'Generates the native splash screen.');
    if (withFirebase) {
      row('firebase_core',
          'Firebase initialisation — see `docs/FIREBASE_SETUP.md`.');
    }
    if (withFirebaseAuthFeature) {
      row('firebase_auth', 'Email/password and Google sign-in.');
      row('google_sign_in', 'The Google half of the sign-in flow.');
    }
    if (withFirestore) row('cloud_firestore', 'The document database.');
    if (withCrashlytics) {
      row('firebase_crashlytics',
          'Crash reporting, wired into the app-wide error handlers.');
    }
    if (withFirebaseNotifications) {
      row('firebase_messaging', 'Push notifications (FCM).');
    }
    if (withNotifications) {
      row('flutter_local_notifications', 'Notifications scheduled on-device.');
    }
    if (withBiometric) row('local_auth', 'Face ID / fingerprint unlock.');
    if (withEasyLocalization) {
      row('easy_localization',
          'Translations from JSON in `assets/translations/`.');
    }
    if (withFlavors) {
      row('flutter_flavorizr',
          'Dev dependency. Generates the native flavor configuration — see section 8.');
    }
    row('build_runner', 'Dev dependency. Runs the code generators.');
    row('mogen_unit_tests',
        'Dev dependency. Generates unit tests from the code you have written.');
    row('flutter_lints',
        'Dev dependency. The lint set `analysis_options.yaml` builds on.');
    if (bloc) {
      row('bloc_lint',
          "Dev dependency. The bloc team's own rules — run with `bloc lint .`.");
    }

    return '''
## 3. Tech stack & tools

| Tool | Purpose | Link |
|---|---|---|
| Flutter | The UI framework — one codebase, both platforms | [flutter.dev](https://flutter.dev) |
| Dart | The language | [dart.dev](https://dart.dev) |
| FVM | Pins the Flutter version this project builds with | [fvm.app](https://fvm.app) |
| VS Code / Android Studio | Editor and debugger | — |
| Xcode | iOS builds, signing and simulators (macOS only) | Mac App Store |
| Android Studio | Android SDK, emulator, build tools | — |
| Git | Version control | — |
| GitHub Actions | CI and release builds — `.github/workflows/` | [docs](https://docs.github.com/actions) |${withFirebase ? '\n| Firebase | Backend services — see `docs/FIREBASE_SETUP.md` | [console](https://console.firebase.google.com) |' : ''}
| Figma | `[link to the design file]` | — |

### Packages

Everything comes from [pub.dev](https://pub.dev) and is declared in
`pubspec.yaml` with a version constraint — never an unbounded one, so a
`pub get` cannot walk the project onto a major release nobody asked for.

These are the ones that shape how the code is written; `pubspec.yaml` is the
complete list.

| Package | What it does here |
|---|---|
${packages.toString().trimRight()}

---
''';
  }

  /// Section 4 — the annotated tree. Only folders the project actually has
  /// are listed, so nothing here points at a path that was never generated.
  static String _structure({
    required bool bloc,
    required bool withRouter,
    required bool withAuthFeature,
    required bool withFirebase,
    required bool withFlavors,
    required bool withLocalization,
  }) {
    final feature = withAuthFeature ? 'auth' : 'profile';
    final presentation = bloc
        ? '''│       └── presentation/
│           ├── blocs/                   # events, states and the bloc
│           ├── pages/                   # the route target: provides the bloc
│           └── views/                   # the screen itself'''
        : '''│       └── presentation/
│           ├── notifiers/               # the AsyncNotifier
│           ├── states/                  # its immutable state class
│           └── views/                   # the screens''';

    return '''
## 4. Project structure

```
lib/
├── config/                          # How the app is wired together
│   ├── di/injector.dart             # get_it registrations — the wiring
│   ├── env/app_env.dart             # the compiled-in .env values
│   ├── theme/app_theme.dart         # colours, typography, component themes
${withRouter ? '│   ├── router/                      # GoRouter routes + the auth redirect\n' : ''}${withFirebase ? '│   ├── firebase/                    # Firebase instances, behind providers\n' : ''}│   └── ...
├── core/                            # Shared by every feature, owned by none
│   ├── constants/                   # App and API constants
│   ├── errors/app_exception.dart    # the one error type the UI ever sees
│   ├── network/                     # HTTP client + the safe call wrappers
│   ├── security/                    # secure storage, validation, biometrics
│   ├── services/                    # notifications, media, permissions, …
│   └── utils/                       # logger, extensions${bloc ? '' : ', runAction'}
├── features/                        # One folder per feature — the app itself
│   └── $feature/
│       ├── domain/
│       │   ├── entities/                # plain Dart objects, no packages
│       │   └── repositories/            # the interfaces the UI depends on
│       ├── data/
│       │   ├── models/                  # entities + fromJson / toJson
│       │   ├── datasources/             # where the bytes actually come from
│       │   └── repositories/            # the implementations
$presentation
├── shared/widgets/                  # The UI kit — see docs/UI_KIT.md
${withLocalization ? '├── l10n/                            # Translation files\n' : ''}${withFlavors ? '├── flavors.dart                     # generated by flutter_flavorizr\n' : ''}└── main.dart                        # the entry point
```

At the root:

| Path | What it is |
|---|---|
| `pubspec.yaml` | Dependencies and the app version |
| `.fvmrc` | The pinned Flutter version — see section 2 |
| `.env` / `.env.example` | Environment values; the first is gitignored, the second is not |
| `analysis_options.yaml` | The lint contract — see section 11 |
| `.moarch.yaml` | Hashes of every generated file, so `moarch update` knows what you edited |
| `flutter_native_splash.yaml` | Native splash configuration |${withFlavors ? '\n| `flavorizr.yaml` | The flavor definitions — see section 8 |' : ''}
| `docs/` | The guides — see section 13 |
| `.github/workflows/` | CI and release builds — see section 10 |
| `android/` `ios/` | The native shells: signing, permissions, platform config |
| `test/` | `unit/` and `integration/` |

Two rules keep those folders meaningful:

- **`core/` holds no feature logic, `shared/widgets/` holds no business logic.**
  If two features need it and it draws pixels, it is a shared widget; if it does
  not, it is in `core/`.
- **A feature never imports another feature's `data/` layer.** If two features
  need the same data, the repository belongs to whichever owns it, and the other
  depends on its `domain` interface.

---
''';
  }

  /// Section 5 — one piece of data traced from the API to the screen, which is
  /// the only way the three folders stop looking like ceremony.
  static String _architecture({required bool bloc, required bool withDio}) =>
      '''
## 5. How the architecture works

Follow one piece of data from the server to the screen. This is a `profile`
feature; every feature in `lib/features/` has the same shape.

### `domain/` — the rules

An **entity** is a plain Dart object. No JSON, no packages, no Flutter:

```dart
// lib/features/profile/domain/entities/profile_entity.dart
class ProfileEntity {
  const ProfileEntity({required this.id, required this.name});

  final String id;
  final String name;
}
```

A **repository interface** is what the feature promises it can do — never how:

```dart
// lib/features/profile/domain/repositories/profile_repository.dart
abstract interface class ProfileRepository {
  Future<List<ProfileEntity>> fetchAll();
}
```

Nothing under `domain/` imports ${withDio ? 'Dio, ' : ''}Firebase or Flutter. That is the
point: these files can be tested with a plain `dart test`, and they survive
every change to the API, the client and the UI.

### `data/` — the world

A **model** is the entity plus serialisation:

```dart
// lib/features/profile/data/models/profile_model.dart
class ProfileModel extends ProfileEntity {
  const ProfileModel({required super.id, required super.name});

  factory ProfileModel.fromJson(Map<String, dynamic> json) => ProfileModel(
        id: json['id'] as String,
        name: json['name'] as String,
      );

  Map<String, dynamic> toJson() => {'id': id, 'name': name};
}
```

It **extends** the entity, so it can be returned anywhere an entity is
expected. The UI is handed `ProfileEntity` and never learns that JSON exists.

A **datasource** is where the bytes come from${withDio ? ' — an HTTP call through the shared\nDio client' : ''}. A **repository implementation** puts
the two together and is the only class that satisfies the interface:

```dart
// lib/features/profile/data/repositories/profile_repository_impl.dart
class ProfileRepositoryImpl implements ProfileRepository {
  ProfileRepositoryImpl(this._remote);

  final ProfileRemoteDataSource _remote;

  @override
  Future<List<ProfileEntity>> fetchAll() => _remote.fetchAll();
}
```

### The wiring: `lib/config/di/injector.dart`

One file knows both sides — which implementation answers which interface. It
uses **get_it**, a service locator:

```dart
getIt.registerLazySingleton<ProfileRepository>(
  () => ProfileRepositoryImpl(getIt<ProfileRemoteDataSource>()),
);
```

Anywhere else in the app, `getIt<ProfileRepository>()` hands back that instance
— and the caller only ever sees the interface type.

- `registerLazySingleton` — built on first use, one instance for the app's life.
  The default for repositories and services.
- `registerFactory` — a new instance every call.

> ⚠️ `injector.dart` contains a `// moarch:registrations` comment.
> `moarch create feature` inserts new registrations directly above it. Keep the
> line where it is or the tooling has nothing to anchor to.

### Errors: exactly one type reaches the UI

Everything that can fail is funnelled into `AppException`
(`lib/core/errors/app_exception.dart`)${withDio ? ', by the `safeApiCall` wrapper in\n`lib/core/network/`' : ''}. A widget never sees a
`DioException`, a `FirebaseException` or a `SocketException` — it sees an
`AppException` with a `message` written for a person.

```dart
// ✅ the data layer translates, the UI displays
try {
  final profiles = await repository.fetchAll();
  // …
} on AppException catch (e) {
  // e.message is safe to show
}

// ❌ never
try {
  // …
} catch (_) {}                       // a swallowed error is a bug you cannot find
catch (e) { showDialog(text: '\$e'); }  // stack traces are not user-facing
```

Two rules follow from that, and section 11 repeats them because they are the
ones most often broken:

1. **Never leave a `catch` empty.** Log it or handle it.
2. **Never show a raw error.** Show `AppException.message`.

---
''';

  /// Section 6, Riverpod variant.
  static String _riverpodGuide() => r'''
## 6. State management — Riverpod

Screens do not hold their own state. Each feature has a **notifier** that owns
one immutable **state** object, and the screen watches it.

### The state

An immutable class in `presentation/states/profile_state.dart`:

```dart
class ProfileState implements ActionState<ProfileState> {
  const ProfileState({this.items = const [], this.success, this.error});

  final List<ProfileEntity> items;
  final String? success;
  final String? error;

  @override
  ProfileState copyWith({List<ProfileEntity>? items, String? success}) =>
      ProfileState(items: items ?? this.items, success: success);
}
```

Immutable means you never change it in place — you build the next one with
`copyWith`. Riverpod compares the old state with the new one to decide what
rebuilds; mutating in place leaves it nothing to compare.

### The notifier

`presentation/notifiers/profile_notifier.dart`:

```dart
final profileNotifierProvider =
    AsyncNotifierProvider<ProfileNotifier, ProfileState>(ProfileNotifier.new);

class ProfileNotifier extends AsyncNotifier<ProfileState>
    with ActionNotifierMixin<ProfileState> {
  ProfileRepository get _repo => getIt<ProfileRepository>();

  @override
  FutureOr<ProfileState> build() async {
    final items = await _repo.fetchAll();
    return ProfileState(items: items);
  }

  Future<void> rename(String id, String name) {
    return runAction((current) async {
      await _repo.rename(id, name);
      return current.copyWith(success: 'Saved');
    });
  }
}
```

Three things worth noticing:

- **`build()` is the initial load, and it is the loading state.** While its
  future runs the provider is `AsyncLoading`; if it throws, `AsyncError`. There
  is no `isLoading` boolean to set or forget.
- **`runAction` is every action after that.** It comes from
  `ActionNotifierMixin` (`lib/core/utils/action_notifier.dart`) and handles the
  loading flag, `AppException` and unknown errors for you. It hands you the
  state as it was before the action; return the state that should follow.
- **The repository comes out of `getIt`, not out of another provider.**
  `injector.dart` owns the data layer; the notifier is the seam between it and
  Riverpod.

### Reading it in a widget

```dart
class ProfileView extends ConsumerWidget {
  const ProfileView({super.key});

  @override
  Widget build(BuildContext context, WidgetRef ref) {
    final state = ref.watch(profileNotifierProvider);

    return state.when(
      loading: () => const Center(child: CircularProgressIndicator()),
      error: (error, _) => Text('Something went wrong'),
      data: (profile) => ListView(
        children: [for (final item in profile.items) Text(item.name)],
      ),
    );
  }
}
```

| You want to | Use |
|---|---|
| rebuild when the state changes | `ref.watch(provider)` |
| call a method from a callback | `ref.read(provider.notifier).rename(...)` |
| react without rebuilding (snackbar, navigation) | `ref.listen(provider, ...)` |
| force a reload | `ref.invalidate(provider)` |

> ⚠️ `ref.watch` belongs in `build`, `ref.read` in callbacks — never the other
> way round. Watching inside a callback reads a value that will not update;
> reading inside `build` gives you a screen that never rebuilds.

`ProviderScope` wraps the whole app in `main.dart`. That is what makes every
provider reachable — if a provider throws "no ProviderScope found", something
was mounted above it.

---
''';

  /// Section 6, bloc variant.
  static String _blocGuide() => r'''
## 6. State management — Bloc

Screens do not hold their own state. Each feature has a **bloc**: it receives
**events** and emits **states**. The screen sends events and rebuilds on states.
Nothing else moves between them.

### The events

A sealed family in `presentation/blocs/profile_event.dart`:

```dart
sealed class ProfileEvent extends Equatable {
  const ProfileEvent();

  @override
  List<Object?> get props => const [];
}

final class ProfileStarted extends ProfileEvent {
  const ProfileStarted();
}

final class ProfileRefreshed extends ProfileEvent {
  const ProfileRefreshed();
}
```

### The states

```dart
sealed class ProfileState extends Equatable { ... }

final class ProfileInitial extends ProfileState { ... }
final class ProfileLoading extends ProfileState { ... }
final class ProfileSuccess extends ProfileState {
  const ProfileSuccess({required this.items});
  final List<ProfileEntity> items;

  @override
  List<Object?> get props => [items];
}
final class ProfileFailure extends ProfileState { ... }
```

**Equatable is not decoration here.** Bloc drops an `emit` whose state equals
the current one, and `BlocBuilder` rebuilds on the same test. A state that
forgets its `props` repaints the screen on every emit.

### The bloc

```dart
class ProfileBloc extends Bloc<ProfileEvent, ProfileState> {
  ProfileBloc() : super(const ProfileInitial()) {
    on<ProfileStarted>(_onStarted);
    on<ProfileRefreshed>(_onStarted);
  }

  ProfileRepository get _repo => getIt<ProfileRepository>();

  Future<void> _onStarted(
    ProfileEvent event,
    Emitter<ProfileState> emit,
  ) async {
    if (state is! ProfileSuccess) emit(const ProfileLoading());
    try {
      emit(ProfileSuccess(items: await _repo.fetchAll()));
    } on AppException catch (e) {
      emit(ProfileFailure(e.message));
    }
  }
}
```

- The repository comes out of `getIt` — `injector.dart` owns the data layer and
  the bloc is the seam between it and the UI.
- `emit` is only valid inside a handler, and only while it is still running.
  Emitting after an `await` that outlived the handler throws.
- Blocs import `package:bloc/bloc.dart`, not `flutter_bloc` — they stay pure
  Dart, which is what the `avoid_flutter_imports` rule keeps true.

### Using it in a widget

The **page** provides the bloc; the **view** draws it:

```dart
class ProfilePage extends StatelessWidget {
  const ProfilePage({super.key});

  @override
  Widget build(BuildContext context) => BlocProvider(
        create: (_) => ProfileBloc()..add(const ProfileStarted()),
        child: const ProfileView(),
      );
}
```

```dart
BlocBuilder<ProfileBloc, ProfileState>(
  builder: (context, state) => switch (state) {
    ProfileInitial() || ProfileLoading() =>
      const Center(child: CircularProgressIndicator()),
    ProfileSuccess(:final items) => ListView(
        children: [for (final item in items) Text(item.name)],
      ),
    ProfileFailure(:final message) => Text(message),
  },
)
```

That `switch` is exhaustive **because the state is `sealed`** — add a new state
and this stops compiling until you handle it. That is the whole reason for the
sealed hierarchy: an unhandled case is a compile error, not a blank screen.

| You want to | Use |
|---|---|
| rebuild on new state | `BlocBuilder` |
| side effect only (snackbar, navigation) | `BlocListener` |
| both at once | `BlocConsumer` |
| send an event | `context.read<ProfileBloc>().add(const ProfileRefreshed())` |
| read the current state without rebuilding | `context.read<ProfileBloc>().state` |

> ⚠️ `context.watch` belongs in `build`, `context.read` in callbacks — never
> the other way round.

On top of the analyzer, the bloc team's own rules run separately:

```bash
dart pub global activate bloc_tools
bloc lint .
```

They cover file naming, Flutter imports inside a bloc, and public fields on a
state. The ruleset is in `analysis_options.yaml`.

---
''';

  /// Section 7 — the generators, and the five steps that are still yours.
  static String _addingAFeature({
    required bool bloc,
    required bool withRouter,
  }) {
    final stateStep = bloc
        ? '''3. **Hold the screen's state.** Add an event to `profile_event.dart`,
   register it with `on<ProfileSomething>(...)` in the bloc's constructor, and
   emit the states it produces.'''
        : '''3. **Hold the screen's state.** Add the fields to `profile_state.dart`
   (and to `copyWith`), then add methods to the notifier — wrap each one in
   `runAction` so loading and errors are handled for you.''';

    return '''
## 7. Adding a feature

The layers are regular enough to generate. From the project root:

```bash
moarch create feature profile
```

That scaffolds `lib/features/profile/` with the layers you tick, registers the
repository in `injector.dart` above the `// moarch:registrations` anchor, and
generates the presentation layer in this project's stack:
${bloc ? 'the bloc, its sealed event and state families, and the page that provides\nit to the widget tree.' : 'the notifier and the immutable state class it owns.'}

Then the part that is yours:

1. **Describe the data.** Fields on `profile_entity.dart`, and the matching
   `fromJson` / `toJson` on `profile_model.dart`.
2. **Say what the feature can do.** Methods on the repository *interface*,
   implemented in `profile_repository_impl.dart`, with the actual call in the
   datasource.
$stateStep
4. **Draw it.** Build the view out of `lib/shared/widgets/` rather than raw
   Material widgets — the kit is catalogued in `docs/UI_KIT.md`.
${withRouter ? '5. **Route to it.** Add the path to `lib/config/router/app_routes.dart` and\n   the route to `app_router.dart`.\n' : ''}
### The other generators

| Command | What it does |
|---|---|
| `moarch create feature <name>` | A whole feature, layers selectable |
| `moarch create model <feature> <name>` | A model + entity inside an existing feature |${bloc ? '\n| `moarch create bloc <feature> <name>` | Another state + event + bloc trio |' : ''}
| `moarch create widget <name>` | A widget from the kit (`docs/UI_KIT.md`) |
| `moarch create entity-copys [feature]` | Injects `copyWith`, `==` and `hashCode` into every entity |
| `moarch create empty-factories [feature]` | Injects `.empty()` factories into every entity |
| `moarch create theme` | Switches the project between one theme and light + dark |
| `moarch create flavors [names…]` | See section 8 |
| `moarch update --list` | Which generated files are out of date, and which you have edited |
| `moarch doctor` | Checks the project for known problems (`--fix` applies what it can) |

### Tests

Tests live in `test/unit/` and `test/integration/`:

```bash
fvm flutter test
```

The scaffold ships no tests of its own beyond the smoke test —
`mogen_unit_tests` and `mogen_integration_tests` are installed as dev
dependencies to generate them from the code you write.

---
''';
  }

  /// Section 8 — flavors. The project usually has none at `init` time, so this
  /// is either the setup path or the per-flavor commands, never both.
  static String _flavorsSection({
    required List<String> flavors,
    required String projectName,
    required bool withFirebase,
  }) {
    final has = flavors.isNotEmpty;
    final list = flavors.map((f) => '`$f`').join(', ');
    final first = has ? flavors.first : 'dev';

    final intro = has
        ? '''This project's flavors are $list, declared in `flavorizr.yaml`. Run one with:

```bash
fvm flutter run --flavor $first
```

Building a particular flavor is section 9.
'''
        : '''This project does **not** have flavors yet. Add them the day it needs more
than one environment installed at a time:

```bash
moarch create flavors dev staging prod
fvm flutter pub get
dart run flutter_flavorizr
```

Review the app names and ids in the generated `flavorizr.yaml` before running
the second command. Until then `fvm flutter run` builds the single app, and
per-environment values come from `.env` (section 2, step 3).
''';

    return '''
## 8. Flavors & environments

A **flavor** is the same codebase built as a different app: its own display
name, its own application id / bundle id, its own backend. That is what lets a
`dev` and a `prod` build of $projectName sit on one device at the same time
instead of overwriting each other.

$intro
### How it is put together

[**flutter_flavorizr**](https://pub.dev/packages/flutter_flavorizr) owns the
native side. `flavorizr.yaml` declares the flavors; `dart run flutter_flavorizr`
writes them into:

- `android/app/build.gradle(.kts)` — the `productFlavors` block
- `android/app/src/main/AndroidManifest.xml`
- the iOS xcconfigs, `Info.plist` and the Xcode schemes
- `lib/flavors.dart` — the Dart side

**There is only one `main.dart`.** No `main_dev.dart` / `main_prod.dart`: the
`instructions` list in `flavorizr.yaml` runs the native processors and the
Dart-side generator only, and never touches the entry point. Read the current
flavor off the generated `lib/flavors.dart` (`F.appFlavor`, `F.name`,
`F.title`) wherever behaviour has to differ.

To add or rename a flavor, edit `flavorizr.yaml` and re-run
`dart run flutter_flavorizr`.

### What catches people out

- **Suffixed ids.** Every non-production flavor gets its id suffixed
  (`com.example.app.dev`). That suffix is exactly what makes side-by-side
  installs possible — do not "tidy" it away.${withFirebase ? '\n- **Firebase is keyed by application id.** Each suffixed id needs its own app\n  registered in the Firebase project, and then `flutterfire configure` re-run.\n  A flavor without one fails at `Firebase.initializeApp`.' : ''}
- **`.vscode/launch.json`** already carries flavored entries. They fail with
  "Could not find product flavor" / "does not define custom schemes" until
  flavorizr has actually run.
- **CI passes `--flavor` too.** A flavored project needs the flag added to the
  build workflows, or the runner builds the unflavored target and fails.
- **Flavors are not `.env`.** Flavors change *which app* is built; `.env`
  changes *the values it is built with*. Most projects need both.

---
''';
  }

  /// Section 9 — the build commands and where the artefacts land.
  static String _building({required List<String> flavors}) {
    final has = flavors.isNotEmpty;
    final flavor = has ? flavors.last : 'prod';
    final flag = has ? ' --flavor $flavor' : '';
    final apk = has ? 'app-$flavor-release.apk' : 'app-release.apk';
    return '''
## 9. Building the app

| Mode | Command | When |
|---|---|---|
| debug | `fvm flutter run` | day to day — this is the one with hot reload |
| profile | `fvm flutter run --profile` | measuring jank; never measure it in debug |
| release | `fvm flutter run --release` | checking real performance and size |

### Android

```bash
fvm flutter build apk$flag --release
# → build/app/outputs/flutter-apk/$apk

fvm flutter build appbundle$flag --release
# → build/app/outputs/bundle/release/app${has ? '-$flavor' : ''}-release.aab
```

The **APK** is for sideloading and QA; the **AAB** is what Google Play accepts.
${has ? 'With flavors the artefact name carries the flavor, which is how you tell two\nbuilds apart on a shared drive.\n' : ''}
A release build has to be **signed** or it installs nowhere. Generating the
keystore and wiring it into Gradle is `docs/GENERATE_JKS_FILE.md`.

### iOS

Needs a Mac with Xcode — or the GitHub Actions workflow in section 10, which is
there precisely so that a Mac is not required.

```bash
fvm flutter build ipa$flag --release
# → build/ios/ipa/*.ipa
```

Distribute it with Transporter or Xcode's Organizer. Producing the signing
certificate and the provisioning profile — including without a Mac — is
`docs/STEPS_FOR_WORKFLOW.md`.

### Before shipping

Two checklists, both in `docs/`, both written to be worked through rather than
read:

- `docs/CHECKLIST_BEFORE_DEPLOYMENT.md` — everything a release needs.
- `docs/SECURITY_BEFORE_DEPLOYMENT.md` — the security review, mapped to the
  OWASP Mobile Top 10.

---
''';
  }

  /// Section 10 — the workflows and the secrets they read. The base64 recipes
  /// themselves stay in `docs/STEPS_FOR_WORKFLOW.md`; duplicating them here
  /// would guarantee the two copies drift.
  static String _cicd({
    required bool withWorkflows,
    required bool withFirebase,
  }) {
    if (!withWorkflows) {
      return '''
## 10. CI/CD & GitHub secrets

This project has no GitHub Actions workflows. If you add them, the secrets and
the signing material they need are documented in
`docs/STEPS_FOR_WORKFLOW.md` (iOS certificate, provisioning profile, base64
encoding) and `docs/GENERATE_JKS_FILE.md` (the Android keystore).

---
''';
    }
    return '''
## 10. CI/CD & GitHub secrets

Five workflows live in `.github/workflows/`:

| Workflow | File | Runs on | What it does |
|---|---|---|---|
| CI | `unified_workflow.yml` | push to `main`/`develop`, PRs to `main` | format, analyze, test, build |
| CSA | `csa.yml` | push and manual | code scanning: SAST, secret scan, SBOM, licence report |
| Build IOS IPA | `build_ipa.yml` | manual | signs and builds the IPA, uploaded as the `release-ipa` artifact |
| Build ANDROID APK | `build_apk.yml` | manual | signs and builds the APK, uploaded as the `release-apk` artifact |
| Fastlane Deploy | `deploy_stores.yml` | manual | uploads a build to App Store Connect / Play Console |

"Manual" means **Actions → the workflow → Run workflow**. Both build workflows
check for their secrets first and **skip cleanly** when they are missing, rather
than failing — so a fresh clone or a fork stays green until signing is set up.

### The secrets

Repository → **Settings → Secrets and variables → Actions**.

| Secret | Used by | Value |
|---|---|---|
| `BASE_URL` | all workflows | the API base URL compiled into the build |
| `IOS_P12_BASE64` | `build_ipa` | base64 of your `.p12` (certificate + private key) |
| `IOS_P12_PASSWORD` | `build_ipa` | the password you set when exporting the `.p12` |
| `IOS_PROVISIONING_PROFILE_BASE64` | `build_ipa` | base64 of your `.mobileprovision` |
| `IOS_TEAM_ID` | `build_ipa` | your Apple Developer Team ID |
| `ANDROID_KEYSTORE_BASE64` | `build_apk` | base64 of your `.jks` keystore |
| `KEYSTORE_STORE_PASSWORD` | `build_apk` | the keystore's store password |
| `KEYSTORE_KEY_PASSWORD` | `build_apk` | the key's password |
| `KEYSTORE_KEY_ALIAS` | `build_apk` | the key alias, e.g. `my-key-alias` |

**Why base64?** A GitHub secret holds text, and a `.p12`, a `.mobileprovision`
and a `.jks` are binary files. Base64 is how a binary becomes a secret: the
workflow decodes it back into a file on the runner, imports it into a temporary
keychain, and that keychain dies with the job.

### Where the step-by-step lives

- **`docs/STEPS_FOR_WORKFLOW.md`** — every secret in the table, produced from
  scratch. The iOS half walks through generating the private key, the signing
  request, converting Apple's `.cer`, bundling the `.p12` and creating the
  provisioning profile **with OpenSSL, so no Mac is needed**, and ends with the
  exact PowerShell one-liners that base64 the `.p12` and the
  `.mobileprovision`.
- **`docs/GENERATE_JKS_FILE.md`** — the Android release keystore and its
  base64.${withFirebase ? '\n- Push notifications add one ordering trap: the Push Notifications capability\n  has to be enabled on the App ID **before** the provisioning profile is\n  generated, or codesigning fails on a missing `aps-environment` entitlement.\n  `docs/STEPS_FOR_WORKFLOW.md` covers it.' : ''}

> 🔐 The `.p12`, the `.mobileprovision` and the `.jks` are **never** committed.
> They belong in the password manager and in GitHub secrets, nowhere else.

---
''';
  }

  /// Section 11 — the conventions the analyzer cannot check for you.
  static String _standards({
    required bool bloc,
    required bool withDarkTheme,
  }) =>
      '''
## 11. Code standards

### Naming

| Element | Convention | Example |
|---|---|---|
| Files and folders | `snake_case` | `profile_view.dart` |
| Classes, enums, extensions | `PascalCase` | `Profile${bloc ? 'Bloc' : 'Notifier'}` |
| Variables and methods | `camelCase` | `fetchProfile()` |
| Private members | leading `_` | `_repo`, `_ProfileHeader` |
| Constants | `camelCase` | `defaultPadding` |

### Widgets

- **Small and reusable beats one long `build`.** When a `build` method grows a
  section, extract it as a *private widget class* (`_ProfileHeader`), not as a
  `Widget _buildHeader()` method. A class gets its own `const` constructor and
  its own rebuild boundary; a method is rebuilt with its parent every time.
- **`const` wherever it compiles.** A `const` widget is skipped entirely on
  rebuild.

```dart
const AppButton(label: 'Save');   // ✅
AppButton(label: 'Save');         // ❌ when it could have been const
```

- **Reach for `lib/shared/widgets/` before Material.** The kit is catalogued in
  `docs/UI_KIT.md`, and `moarch create widget <name>` adds one on demand.${withDarkTheme ? '\n- **Never hard-code a `Color`.** The palette has a dark half; a literal colour\n  does not follow it. Take colours from the theme or from `AppConstants`.' : ''}

### Errors

- Never leave a `catch` empty — log it or handle it. A swallowed exception is a
  bug nobody can find.
- Never show a raw error or a stack trace in the UI. Catch `AppException` and
  show its `message`.
- Translate at the boundary: the datasource turns transport errors into
  `AppException`, so the UI has one type to handle. Section 5 has the pattern.

### Before every commit

```bash
fvm dart format .
fvm flutter analyze
fvm flutter test
```

The CI workflow checks formatting, runs the analyzer and runs the tests, and
fails the build on any of them — so running all three locally only ever saves a
round trip. The rules themselves are in `analysis_options.yaml`.${bloc ? "\n\n`bloc lint .` is separate: the bloc team's ruleset is not part of CI, and\nsection 6 has the one-time setup it needs." : ''}

---
''';

  /// Section 12 — the part no detection can fill in. Deliberately shipped as
  /// `[bracketed]` prompts: a blank table gets skipped, a bracketed one gets
  /// noticed.
  static String _contacts({required bool withFirebase}) => '''
## 12. Contacts & access

> 🔐 **Passwords and tokens must never be stored in this file.** It is in the
> repository; the repository is not a vault.

### Accounts

| Service | Account / email | Where the password lives |
|---|---|---|
| Git repository | `[username]` | `[password manager]` |
| Google Play Console | `[email]` | `[password manager]` |
| Apple Developer / App Store Connect | `[email / Apple ID]` | `[password manager]` |${withFirebase ? '\n| Firebase | `[email]` | `[password manager]` |' : ''}

### Certificates & keys

| Item | Where it lives |
|---|---|
| Android keystore (`.jks`) | `[password manager / secure storage]` |
| Keystore passwords and alias | `[password manager]` |
| iOS certificate (`.p12`) and its password | `[password manager]` |
| Provisioning profiles (`.mobileprovision`) | `[password manager]` |
| API keys | `[.env, and GitHub secrets for CI]` |

> ⚠️ **Never commit** keystores, certificates, provisioning profiles, `.env` or
> API keys. `.gitignore` covers the usual ones; it cannot cover a file you
> renamed.

### People

| Role | Name | Contact |
|---|---|---|
| Mobile developer | `[name]` | `[email]` |
| Backend / API | `[name]` | `[email]` |
| Design | `[name]` | `[email]` |
| Product owner / manager | `[name]` | `[email]` |

---
''';

  /// Section 13 — where every other document is, and the reading order for
  /// someone new to Flutter.
  static String _links({
    required bool bloc,
    required bool withDio,
    required bool withRouter,
    required bool withFirebase,
    required bool withLocalization,
    required bool withEasyLocalization,
    required bool withBiometric,
  }) {
    final stateDocs = bloc
        ? '- [Bloc library](https://bloclibrary.dev) — concepts, testing, the naming conventions this project follows'
        : '- [Riverpod](https://riverpod.dev) — providers, `AsyncValue`, and when to watch vs. read';

    return '''
## 13. Documentation & links

### In this repository

| Document | What it answers |
|---|---|
| `docs/UI_KIT.md` | Every shared widget, what it takes and what it looks like |
| `docs/CHECKLIST_BEFORE_DEPLOYMENT.md` | What still needs doing before a release |
| `docs/SECURITY_BEFORE_DEPLOYMENT.md` | The security review, mapped to the OWASP Mobile Top 10 |
| `docs/GENERATE_JKS_FILE.md` | Creating the Android signing keystore, and its base64 |
| `docs/STEPS_FOR_WORKFLOW.md` | Every GitHub secret the workflows need, produced step by step |${withFirebase ? '\n| `docs/FIREBASE_SETUP.md` | The console and platform steps the generated Firebase code depends on |' : ''}

### If Flutter is new to you

Read these in order — a day, and the rest of this file will read easily:

1. [Write your first Flutter app](https://docs.flutter.dev/get-started/codelab)
   — a couple of hours, hands on.
2. [Introduction to widgets](https://docs.flutter.dev/ui/widgets-intro) — why
   everything is a widget, and what stateless vs. stateful means.
3. [Effective Dart](https://dart.dev/effective-dart) — the style the analyzer
   enforces here.
4. ${bloc ? '[Bloc: core concepts](https://bloclibrary.dev/bloc-concepts/)' : '[Riverpod: getting started](https://riverpod.dev/docs/introduction/getting_started)'}
   — then re-read section 6 of this file.
5. [Flutter Cookbook](https://docs.flutter.dev/cookbook) — the recipe you need,
   when you need it.

### Reference

- [Flutter documentation](https://docs.flutter.dev) · [API reference](https://api.flutter.dev)
- [Dart documentation](https://dart.dev/guides) · [pub.dev](https://pub.dev)
$stateDocs
- [get_it](https://pub.dev/packages/get_it) — the service locator behind `injector.dart`${withDio ? '\n- [Dio](https://pub.dev/packages/dio) — the HTTP client' : ''}${withRouter ? '\n- [go_router](https://pub.dev/packages/go_router) — routing and redirects' : ''}${withFirebase ? '\n- [Firebase for Flutter](https://firebase.google.com/docs/flutter/setup)' : ''}${withLocalization || withEasyLocalization ? '\n- [Internationalizing Flutter apps](https://docs.flutter.dev/ui/accessibility-and-internationalization/internationalization)' : ''}${withBiometric ? '\n- [local_auth](https://pub.dev/packages/local_auth) — biometric authentication' : ''}
- [FVM](https://fvm.app) — the Flutter version manager
- [flutter_flavorizr](https://pub.dev/packages/flutter_flavorizr) — flavors
- [moarch](https://pub.dev/packages/moarch) — the generator this scaffold came from

---
''';
  }

  /// The closing note. Aimed at whoever inherits the file, since a README that
  /// nobody is told to maintain is a README that stops being true.
  static const _footer = r'''
> 📝 **Keeping this file true**
>
> Update it whenever the stack, the structure or the release process changes —
> reviewing it at each major release, or once a quarter, is enough to keep it
> from quietly going stale. The `[bracketed]` placeholders above are the parts
> only your team can fill in.
>
> The generated sections can be refreshed with `moarch update readme --diff` to
> see what changed first. Once you have edited this file it is yours: the
> generator will not overwrite it without `--force`.
''';
}
