class TestTemplates {
  TestTemplates._();

  // ── test_helper.dart ────────────────────────────────────────────────────────
  // Shared across all integration tests.
  // Builds a test-ready Dio instance without auth or interceptors.

  static String testHelper() => r'''
import 'package:dio/dio.dart';
import '../lib/config/env/app_env.dart';

import '../lib/core/constants/api_constants.dart';

/// Builds a clean Dio instance for integration tests.
Dio buildTestDio() {

  return Dio(
    BaseOptions(
      baseUrl: AppEnv.baseUrl,
      connectTimeout: ApiConstants.connectTimeout,
      receiveTimeout: ApiConstants.receiveTimeout,
      headers: const {
        'Content-Type': 'application/json',
        'Accept': 'application/json',
      },
      // Only 2xx passes — anything else throws DioException
      validateStatus: (status) => status != null && status >= 200 && status < 300,
    ),
  );
}
''';

  // ── Integration test ────────────────────────────────────────────────────────
  // Hits the real API directly via the datasource.
  // Verifies: HTTP call succeeds + JSON parses into model + toEntity() works.
  //
  // Test data: use a permanent test account / seed data your team keeps alive.
  // Store credentials as GitHub secrets or in .env — never hardcode them here.
  //
  // Run: flutter test test/integration/features/<n>/

  static String integrationTest(String name, String cls) => '''
// ignore_for_file: avoid_print
import 'package:flutter_test/flutter_test.dart';
import 'package:dio/dio.dart';

import '../../../test_helper.dart';
import '../../../../lib/features/$name/data/datasources/${name}_remote_datasource.dart';
import '../../../../lib/features/$name/data/models/${name}_model.dart';

void main() {

  group('$cls — integration', () {
    late ${cls}RemoteDataSource datasource;

    setUp(() {
      datasource = ${cls}RemoteDataSource(buildTestDio());
    });

    // ── fetchAll ──────────────────────────────────────────────────────────────

    test('fetchAll() returns a list of ${cls}Model', () async {
      final result = await datasource.fetchAll();

      print('[$cls] fetchAll() returned \${result.length} items');
      expect(result, isA<List<${cls}Model>>());
      expect(result, isNotEmpty);
    });

    test('fetchAll() toEntity() converts without throwing', () async {
      final result = await datasource.fetchAll();
      // Full chain: HTTP → JSON → Model → Entity
      expect(() => result.first.toEntity(), returnsNormally);
    });

    test('fetchAll() error', () async {
      // Throws error
      expect(
        () async => await datasource.fetchAll(
          //error data
        ),
        throwsA(isA<DioException>()),
      );
    });

    // TODO: add a test per method — same 2-step pattern:
    // test('myMethod() returns expected type', () async { ... });
    // test('myMethod() toEntity() works', () async { ... });
  });
}
''';

  // ── Notifier test ───────────────────────────────────────────────────────────
  // Uses Mocktail to mock the repository — no manual fake classes.
  // Pattern per method: init check → success → error. That's it.
  //
  // Add to pubspec.yaml dev_dependencies:
  //   mocktail: ^1.0.4

  static String notifierTest(String name, String cls) => '''
import 'package:flutter_riverpod/flutter_riverpod.dart';
import 'package:flutter_test/flutter_test.dart';
import 'package:mocktail/mocktail.dart';
import '../../../../lib/core/errors/app_exception.dart';

import '../../../../lib/features/$name/data/repositories/${name}_repository_impl.dart';
import '../../../../lib/features/$name/domain/entities/${name}_entity.dart';
import '../../../../lib/features/$name/domain/repositories/${name}_repository.dart';
import '../../../../lib/features/$name/presentation/notifiers/${name}_notifier.dart';
import '../../../../lib/features/$name/presentation/states/${name}_state.dart';

// Mock generated by Mocktail — no manual fake class needed
class Mock${cls}Repository extends Mock implements ${cls}Repository {}

void main() {
  late Mock${cls}Repository mockRepo;
  late ProviderContainer container;

  setUp(() {
    mockRepo = Mock${cls}Repository();
    container = ProviderContainer(
      overrides: [
        ${name}RepositoryProvider.overrideWithValue(mockRepo),
      ],
    );
  });

  tearDown(() => container.dispose());

  group('${cls}Notifier', () {

    // ── initial state ─────────────────────────────────────────────────────────

    test('initial state is correct', () async{
      await container.read(${name}NotifierProvider.future);
      final state = container.read(${name}NotifierProvider).requireValue;

      expect(container.read(${name}NotifierProvider), isA<AsyncData<${cls}State>>());
      expect(state.isLoadingAction, false);
      expect(state.error, isNull);
      expect(state.success, isNull);
    });

    // ── fetchAll() ────────────────────────────────────────────────────────────────
    // TODO: replace ${cls}Entity() with real fields once your entity is defined

    test('fetchAll() succeeds', () async {
     await container.read(${name}NotifierProvider.future);
  
      when(() => mockRepo.fetchAll())
          .thenAnswer((_) async => [${cls}Entity()]);

     await container.read(${name}NotifierProvider.notifier).fetchAll();

       final state = container.read(${name}NotifierProvider).value;

      expect(state?.error, isNull);
      expect(state?.isLoadingAction, false);
    });

    test('fetchAll() sets error on failure', () async {
     await container.read(${name}NotifierProvider.future);

      when(() => mockRepo.fetchAll())
          .thenThrow(AppException.test());

      await container.read(${name}NotifierProvider.notifier).fetchAll();

      final state = container.read(${name}NotifierProvider).value;

      expect(state?.error, isNotNull);
      expect(state?.isLoadingAction, false);

     
     
    });

  });
}
''';

  // ── Repository test — kept for reference but not generated by default ───────
  // Only useful if you want to verify DioException → AppException conversion.
  // Most teams skip this once they trust the pattern works.

  /* static String repositoryTest(String name, String cls) => '''
import 'package:dio/dio.dart';
import 'package:flutter_test/flutter_test.dart';
import 'package:mocktail/mocktail.dart';

import '../../../../lib/core/errors/app_exception.dart';
import '../../../../lib/features/$name/data/datasources/${name}_remote_datasource.dart';
import '../../../../lib/features/$name/data/models/${name}_model.dart';
import '../../../../lib/features/$name/data/repositories/${name}_repository_impl.dart';

class Mock${cls}RemoteDataSource extends Mock implements ${cls}RemoteDataSource {}

void main() {
  late Mock${cls}RemoteDataSource mockDatasource;
  late ${cls}RepositoryImpl repo;

  setUp(() {
    mockDatasource = Mock${cls}RemoteDataSource();
    repo = ${cls}RepositoryImpl(mockDatasource);
  });

  group('${cls}RepositoryImpl', () {

    test('fetchAll() returns entities on success', () async {
      when(() => mockDatasource.fetchAll())
          .thenAnswer((_) async => [${cls}Model()]);

      final result = await repo.fetchAll();

      expect(result, isNotEmpty);
    });

    test('fetchAll() throws AppException on DioException', () async {
      when(() => mockDatasource.fetchAll()).thenThrow(
        DioException(requestOptions: RequestOptions(path: '')),
      );

      expect(() => repo.fetchAll(), throwsA(isA<AppException>()));
    });
  });
}
''';
*/
  // ── Use case test ───────────────────────────────────────────────────────────

  static String usecaseTest(String name, String cls) => '''
import 'package:flutter_test/flutter_test.dart';
import 'package:mocktail/mocktail.dart';

import '../../../../lib/features/$name/domain/entities/${name}_entity.dart';
import '../../../../lib/features/$name/domain/repositories/${name}_repository.dart';
import '../../../../lib/features/$name/domain/usecases/get_$name.dart';

class Mock${cls}Repository extends Mock implements ${cls}Repository {}

void main() {
  late Mock${cls}Repository mockRepo;
  late Get$cls useCase;

  setUp(() {
    mockRepo = Mock${cls}Repository();
    useCase = Get$cls(mockRepo);
  });

  group('Get$cls', () {
    test('calls repository once and returns result', () async {
      when(() => mockRepo.fetchAll())
          .thenAnswer((_) async => [${cls}Entity()]);

      final result = await useCase.call();

      verify(() => mockRepo.fetchAll()).called(1);
      expect(result, isNotEmpty);
    });

    test('propagates repository exceptions', () async {
      when(() => mockRepo.fetchAll()).thenThrow(Exception('error'));

      expect(() => useCase.call(), throwsException);
    });
  });
}
''';
}
